import {
  Building2, ShoppingCart, Plug, Bot, RefreshCw, Shield, Globe, Smartphone,
  BarChart3, Search, Mail, Star, Palette, MapPin, Target, Zap, FileText,
  CheckCircle, Bell, Link2, Wrench, Eye, Database, Calendar, MessageSquare,
  Map, Rocket, AlertTriangle, Camera, Shuffle, Lock, ChevronRight,
  MonitorSmartphone, LayoutGrid, Settings, BookOpen, Megaphone, Lightbulb,
  PenTool, Scale, Brain, FlaskConical, ImageIcon, PieChart, Bookmark,
  Server, HardDrive, Cpu, Send, Users, Clock, TrendingUp, Package,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  '🏢': Building2,
  '🛒': ShoppingCart,
  '🔌': Plug,
  '🤖': Bot,
  '🔄': RefreshCw,
  '🔒': Shield,
  '🌐': Globe,
  '🌍': Globe,
  '📱': MonitorSmartphone,
  '📊': BarChart3,
  '🔍': Search,
  '📧': Mail,
  '⭐': Star,
  '🎨': Palette,
  '📍': MapPin,
  '🎯': Target,
  '⚡': Zap,
  '📝': FileText,
  '✅': CheckCircle,
  '🔔': Bell,
  '🔗': Link2,
  '🔧': Wrench,
  '🔮': Eye,
  '🗄️': Database,
  '📅': Calendar,
  '🗣️': MessageSquare,
  '🗺️': Map,
  '🚀': Rocket,
  '🚨': AlertTriangle,
  '📸': Camera,
  '🔀': Shuffle,
  '💾': HardDrive,
  '📐': LayoutGrid,
  '🏗️': Settings,
  '📰': BookOpen,
  '📣': Megaphone,
  '✍️': PenTool,
  '⚖️': Scale,
  '🧠': Brain,
  '🧪': FlaskConical,
  '🖼️': ImageIcon,
  '📋': PieChart,
  '📌': Bookmark,
  '🏷️': Bookmark,
  '💼': Send,
  '💰': TrendingUp,
  '🏪': Package,
  '📈': TrendingUp,
  '📡': Server,
  '🕷️': Search,
  '❓': MessageSquare,
  '🎬': Camera,
  '🗓️': Calendar,
  '👥': Users,
  '⏱️': Clock,
}

export function getIcon(emoji: string): LucideIcon | null {
  return ICON_MAP[emoji] || null
}
