import type { Metadata } from 'next'

type BuildMetadataOptions = {
  title: string
  description: string
  path: string          // e.g. '/services/websites'
  keywords?: string[]
  ogTitle?: string      // defaults to title
  ogDescription?: string // defaults to description
  twitterTitle?: string  // defaults to title
  twitterDescription?: string // defaults to description
  noIndex?: boolean
}

const SITE_URL = 'https://demandsignals.co'

// Dynamic OG image — generated by src/app/opengraph-image.tsx at the edge.
// Next.js metadata API does NOT auto-inject the file-convention image
// when `openGraph` is explicitly set, so we reference it as an absolute
// URL here. Updating the rendered image only requires editing
// src/app/opengraph-image.tsx — no need to touch this constant.
const OG_IMAGE_URL = `${SITE_URL}/opengraph-image`

export function buildMetadata({
  title,
  description,
  path,
  keywords = [],
  ogTitle,
  ogDescription,
  twitterTitle,
  twitterDescription,
  noIndex = false,
}: BuildMetadataOptions): Metadata {
  const url = `${SITE_URL}${path}`

  return {
    /* ── Primary ─────────────────────────────────────── */
    title: { absolute: title }, // bypass layout-level template; page titles already include brand suffix
    description,
    ...(keywords.length > 0 && { keywords }),

    /* ── Indexing ─────────────────────────────────────── */
    robots: noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true, googleBot: { index: true, follow: true, 'max-image-preview': 'large' as const, 'max-snippet': -1, 'max-video-preview': -1 } },

    /* ── Open Graph (social preview cards) ───────────── */
    openGraph: {
      title:       ogTitle ?? title,
      description: ogDescription ?? description,
      url,
      type:        'website',
      siteName:    'Demand Signals',
      locale:      'en_US',
      images: [{
        url:    OG_IMAGE_URL,
        width:  1200,
        height: 630,
        alt:    ogTitle ?? title,
        type:   'image/png',
      }],
    },

    /* ── Twitter / X Card ────────────────────────────── */
    twitter: {
      card:        'summary_large_image',
      title:       twitterTitle ?? ogTitle ?? title,
      description: twitterDescription ?? ogDescription ?? description,
      images:      [OG_IMAGE_URL],
      site:        '@demandsignals',
      creator:     '@demandsignals',
    },

    /* ── Canonical URL ────────────────────────────────── */
    alternates: { canonical: url },
  }
}
