/**
 * All services offered by Demand Signals.
 * Used by city hub pages (/locations/[city]) and long-tail pages (/locations/[city]/[service]).
 */

export type ServiceCategory = 'websites-apps' | 'demand-generation' | 'content-social' | 'ai-services'

export type ServiceData = {
  slug: string
  name: string
  shortName: string
  /** Search-intent name for LTP headings — e.g. "WordPress Developer", "Local SEO Expert" */
  searchIntentName: string
  category: ServiceCategory
  categoryLabel: string
  icon: string
  parentHref: string
  tagline: string
  description: string
  features: string[]
  /** SEO-focused keyword template — {city} and {county} are replaced at render time */
  keywordTemplates: string[]
  /** FAQ templates — {city}, {county}, {state} are replaced at render time */
  faqTemplates: Array<{ question: string; answer: string }>
}

export const SERVICE_CATEGORIES: Record<ServiceCategory, { label: string; color: string }> = {
  'websites-apps': { label: 'Websites & Apps', color: '#3B82F6' },
  'demand-generation': { label: 'Demand Generation', color: '#52C9A0' },
  'content-social': { label: 'Content & Social', color: '#8B5CF6' },
  'ai-services': { label: 'AI & Agents', color: '#FF6B2B' },
}

export const SERVICES: ServiceData[] = [
  // ── Websites & Apps ─────────────────────────────────────────
  {
    slug: 'wordpress-development',
    name: 'WordPress Development',
    shortName: 'WordPress',
    searchIntentName: 'WordPress Developer',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '🌐',
    parentHref: '/websites-apps/wordpress-development',
    tagline: 'Custom WordPress sites built to rank and convert',
    description: 'Custom WordPress websites engineered for speed, SEO performance, and lead conversion. We build sites that rank in Google, appear in AI search results, and turn local visitors into booked appointments.',
    features: ['Custom theme development', 'Core Web Vitals optimized', 'Local schema markup', 'AI content pipeline ready', 'Mobile-first responsive design', 'Ongoing maintenance & updates'],
    keywordTemplates: ['WordPress development {city}', 'WordPress website {city} {state}', 'custom WordPress site {city}', 'WordPress developer near {city}', 'WordPress SEO {city}'],
    faqTemplates: [
      { question: 'How much does a WordPress website cost in {city}?', answer: 'WordPress websites for {city} businesses typically range from $5,000 to $15,000 depending on complexity, custom functionality, and content requirements. This includes custom theme development, local schema markup, Core Web Vitals optimization, and mobile-responsive design. Our AI content pipeline integration means your site launches with optimized content targeting {city} and {county} search terms from day one.' },
      { question: 'Why should a {city} business choose WordPress?', answer: 'WordPress powers over 43% of the web and offers the best balance of flexibility, SEO capability, and long-term maintainability for {city} businesses. Its native SEO architecture supports the structured data, local schema, and content depth that Google and AI search systems reward. For {city} businesses competing in the {county} market, WordPress provides the technical foundation needed to rank across traditional search, AI Overviews, and answer engines simultaneously.' },
      { question: 'How long does it take to build a WordPress website for a {city} business?', answer: 'A typical WordPress build for a {city} business takes 4-8 weeks from kickoff to launch. This includes discovery, wireframing, custom theme development, content creation, local SEO setup, schema markup implementation, and Core Web Vitals optimization. We build city-specific landing pages targeting {city} and surrounding {county} communities as part of the initial launch.' },
      { question: 'Do you provide ongoing WordPress maintenance for {city} businesses?', answer: 'Yes. WordPress requires regular updates to plugins, themes, and core software to maintain security and performance. Our maintenance plans for {city} businesses include daily backups, security monitoring, plugin updates, performance optimization, and content updates. We also continuously optimize for local search performance in the {city} and {county} market.' },
      { question: 'Can you redesign my existing {city} business website on WordPress?', answer: 'Absolutely. We specialize in redesigning outdated websites for {city} businesses — preserving your existing search authority while dramatically improving speed, design, mobile experience, and conversion rates. Our redesign process includes a full SEO audit, URL redirect mapping, local schema implementation, and AI search optimization to ensure your {city} business gains visibility rather than losing it during the transition.' },
    ],
  },
  {
    slug: 'react-next-webapps',
    name: 'React & Next.js Web Apps',
    shortName: 'React / Next.js',
    searchIntentName: 'Web App Developer',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '⚛️',
    parentHref: '/websites-apps/react-next-webapps',
    tagline: 'High-performance web applications built with React and Next.js',
    description: 'Enterprise-grade web applications built with React and Next.js — the same technology powering Netflix, Uber, and this very website. Server-rendered, blazing-fast, and optimized for both users and search engines.',
    features: ['Server-side rendering (SSR)', 'Static site generation (SSG)', 'API route integration', 'TypeScript by default', 'Edge-optimized deployment', 'AI feature integration'],
    keywordTemplates: ['React developer {city}', 'Next.js development {city}', 'web app development {city} {state}', 'React web application {city}', 'custom web app {city}'],
    faqTemplates: [
      { question: 'What is the advantage of React/Next.js over WordPress for {city} businesses?', answer: 'React and Next.js deliver superior performance, interactivity, and scalability compared to WordPress. For {city} businesses with complex requirements — custom dashboards, real-time features, API integrations, or high-traffic applications — Next.js provides sub-second load times, server-side rendering for SEO, and the ability to build features that WordPress simply cannot handle. The performance advantage directly impacts search rankings and conversion rates in the competitive {county} market.' },
      { question: 'How much does a React/Next.js web app cost in {city}?', answer: 'Custom React/Next.js applications for {city} businesses typically range from $10,000 to $50,000+ depending on complexity and feature requirements. This includes architecture design, frontend and backend development, API integrations, deployment on edge infrastructure, and local SEO optimization. The investment is higher than WordPress but delivers dramatically better performance and flexibility for businesses with advanced requirements.' },
      { question: 'How long does it take to build a React/Next.js web app for a {city} business?', answer: 'Most React/Next.js projects for {city} businesses take 6-12 weeks from discovery to launch, depending on feature complexity. Simple marketing sites with dynamic features can ship in 4-6 weeks, while full-stack applications with user authentication, dashboards, and third-party integrations typically require 8-12 weeks. We deploy on edge infrastructure from day one, so your {city} customers experience sub-second load times as soon as the app goes live.' },
      { question: 'Can a React/Next.js app integrate with my existing {city} business systems?', answer: 'Yes — API integration is one of the core strengths of React/Next.js development. We routinely connect web apps to CRMs, payment processors, inventory systems, booking platforms, and AI services for {city} businesses. Next.js API routes allow us to build secure server-side integrations without exposing sensitive credentials to the browser. Whether you need to sync with QuickBooks, Salesforce, or custom internal tools, the architecture supports it natively.' },
      { question: 'Is React/Next.js good for SEO in the {city} market?', answer: 'Excellent. Next.js provides server-side rendering and static generation, which means search engines and AI crawlers see fully-rendered HTML — unlike client-side React apps that can struggle with indexing. We implement local schema markup, dynamic meta tags, and optimized page structures that target {city} and {county} search terms. This site (demandsignals.co) is built with Next.js and ranks across traditional search, AI Overviews, and answer engines — proof that the framework delivers SEO results.' },
    ],
  },
  {
    slug: 'mobile-apps',
    name: 'iOS & Android Mobile Apps',
    shortName: 'Mobile Apps',
    searchIntentName: 'Mobile App Developer',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '📱',
    parentHref: '/websites-apps/mobile-apps',
    tagline: 'Native and cross-platform mobile apps for iOS and Android',
    description: 'Custom mobile applications for iOS and Android that extend your business reach beyond the browser. Built with React Native for cross-platform efficiency, integrated with your existing systems, and optimized for app store visibility.',
    features: ['React Native cross-platform', 'iOS & Android native', 'App Store optimization', 'Push notifications', 'Offline capability', 'API integration'],
    keywordTemplates: ['mobile app development {city}', 'iOS app developer {city}', 'Android app development {city} {state}', 'custom mobile app {city}', 'app developer near {city}'],
    faqTemplates: [
      { question: 'How much does a mobile app cost for a {city} business?', answer: 'Mobile apps for {city} businesses typically range from $15,000 to $75,000+ depending on platform (iOS, Android, or both), feature complexity, and integration requirements. We build with React Native for cross-platform efficiency — one codebase for both iOS and Android — which reduces cost and development time by 40-60% compared to building two native apps.' },
      { question: 'Do {city} businesses really need a mobile app?', answer: 'Not every {city} business needs a dedicated app. We recommend mobile apps when your customers need frequent, repeated interactions — appointment booking, loyalty programs, real-time updates, or offline access. For most local {city} businesses, a fast, mobile-optimized website with progressive web app (PWA) features delivers better ROI than a native app.' },
      { question: 'How long does mobile app development take for a {city} business?', answer: 'A typical React Native mobile app for a {city} business takes 8-16 weeks from concept to app store submission. This includes discovery and UX design (2-3 weeks), development and API integration (4-8 weeks), testing across devices (1-2 weeks), and app store submission and approval (1-3 weeks). Apple and Google review times vary, so we plan for a 1-2 week approval window. Cross-platform development with React Native means iOS and Android launch simultaneously rather than sequentially.' },
      { question: 'What ongoing costs are involved with a mobile app for a {city} business?', answer: 'Beyond the initial build, {city} businesses should budget for: Apple Developer Program ($99/year), Google Play Developer ($25 one-time), hosting and API infrastructure ($50-$500/month depending on usage), and ongoing maintenance and updates ($500-$2,000/month). iOS and Android release regular OS updates that may require app compatibility updates. We offer maintenance plans that cover all updates, bug fixes, performance monitoring, and feature enhancements for {city} business apps.' },
      { question: 'Can you build an app that works offline for {city} service businesses?', answer: 'Yes — offline capability is a core feature we build into apps for {city} field service businesses. Technicians, inspectors, and service providers working across {county} often encounter areas with poor connectivity. Our apps cache critical data locally, queue actions performed offline, and sync automatically when connectivity returns. This means your {city} team can access customer records, complete forms, capture photos, and log work even in areas with no cell service.' },
    ],
  },
  {
    slug: 'vibe-coded',
    name: 'Vibe Coded Web Apps',
    shortName: 'Vibe Coded',
    searchIntentName: 'AI Web App Builder',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '✨',
    parentHref: '/websites-apps/vibe-coded',
    tagline: 'AI-built web applications — rapid development, real results',
    description: 'Web applications built using AI-assisted "vibe coding" — a revolutionary approach where AI writes the code while human experts direct the architecture. 10x faster development, dramatically lower cost, same production quality.',
    features: ['AI-assisted development', '10x faster delivery', 'Lower development cost', 'Human-directed architecture', 'Production-grade output', 'Full customization'],
    keywordTemplates: ['vibe coding {city}', 'AI web development {city}', 'rapid web app development {city}', 'AI-built website {city}', 'fast web development {city} {state}'],
    faqTemplates: [
      { question: 'What is vibe coding and how does it benefit {city} businesses?', answer: 'Vibe coding is an AI-assisted development approach where AI models write production code under human expert direction. For {city} businesses, this means custom web applications delivered in days instead of months, at 50-70% lower cost than traditional development. The output is production-grade, fully customizable, and built with the same modern frameworks (React, Next.js) used by major tech companies.' },
      { question: 'Is a vibe-coded web app as good as a traditionally built one?', answer: 'Yes — and often better. AI-assisted development eliminates many common human coding errors while maintaining the architectural decisions and business logic that experienced developers provide. For {city} businesses, vibe coding delivers the same quality with dramatically faster turnaround and lower cost. Our vibe-coded applications are fully tested, performant, and optimized for both users and search engines.' },
      { question: 'How much does a vibe-coded web app cost for a {city} business?', answer: 'Vibe-coded web applications for {city} businesses typically cost 50-70% less than traditional development — ranging from $3,000 to $15,000 for most projects. The savings come from AI handling the code generation while our senior architects direct the structure, business logic, and quality assurance. For {city} businesses that need custom functionality but have limited budgets, vibe coding makes professional web applications accessible at price points that previously only bought template websites.' },
      { question: 'How fast can a vibe-coded app be delivered for a {city} business?', answer: 'Most vibe-coded applications for {city} businesses ship in 1-3 weeks — compared to 6-12 weeks for traditional development. Simple applications (landing pages with dynamic features, booking systems, dashboards) can launch in under a week. More complex applications with multiple integrations, user roles, and custom workflows typically take 2-3 weeks. This speed advantage is particularly valuable for {city} businesses launching new services or responding to market opportunities quickly.' },
      { question: 'What happens if I need changes to my vibe-coded app after launch?', answer: 'Vibe-coded applications are built with the same production frameworks (React, Next.js, Node.js) as traditionally developed apps — they are fully maintainable and modifiable after launch. Changes, new features, and updates are typically delivered 3-5x faster than traditional development timelines. For {city} businesses, this means your application can evolve rapidly as your needs change without the long development cycles and high costs associated with traditional custom software maintenance.' },
    ],
  },
  {
    slug: 'design',
    name: 'UI/UX Design',
    shortName: 'UI/UX Design',
    searchIntentName: 'Website Designer',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '🎨',
    parentHref: '/websites-apps/design',
    tagline: 'Conversion-optimized design that builds trust and drives action',
    description: 'Professional UI/UX design that reflects the quality of your business. Mobile-first, conversion-optimized interfaces that build trust with local customers from the first click and turn visitors into paying clients.',
    features: ['Mobile-first responsive design', 'Conversion-optimized layouts', 'Brand-consistent visual identity', 'Accessibility compliant', 'User research & testing', 'Design system creation'],
    keywordTemplates: ['UI UX design {city}', 'web design {city} {state}', 'website designer {city}', 'UX design agency {city}', 'responsive web design {city}'],
    faqTemplates: [
      { question: 'Why does professional design matter for {city} businesses?', answer: 'In the {city} market, your website is often the first impression potential customers have of your business. Professional design builds instant trust — studies show visitors form an opinion about your business within 0.05 seconds of landing on your website. For {city} businesses competing against well-established local competitors, a professionally designed website that conveys credibility and quality is the difference between a bounce and a booked appointment.' },
      { question: 'How does UI/UX design impact SEO for {city} businesses?', answer: 'Google directly measures user experience signals — page load speed, mobile responsiveness, layout stability (Core Web Vitals) — as ranking factors. Poor design increases bounce rates and reduces time-on-page, which signals low quality to search algorithms. For {city} businesses targeting local search rankings, professional UI/UX design improves both the human experience and the search engine signals that determine your visibility in the {county} market.' },
      { question: 'How much does professional UI/UX design cost for a {city} business website?', answer: 'Professional UI/UX design for {city} business websites typically ranges from $3,000 to $10,000 depending on the number of pages, complexity of user flows, and whether the project includes user research. This covers wireframing, visual design, mobile and desktop layouts, interactive prototyping, and a design system for consistent future updates. For {city} businesses redesigning an existing site, we include a UX audit that identifies the specific conversion bottlenecks costing you leads.' },
      { question: 'What is the design process for a {city} business website?', answer: 'Our design process for {city} businesses follows five phases: (1) Discovery — we research your industry, competitors in {city} and {county}, and target customer behavior. (2) Wireframing — low-fidelity layouts that map user journeys and conversion paths. (3) Visual design — high-fidelity mockups with your brand colors, typography, and imagery. (4) Prototyping — interactive previews you can click through before development begins. (5) Handoff — development-ready assets with responsive specifications. You review and approve at every stage, so the final design reflects your vision for your {city} business.' },
      { question: 'Do you design for mobile first when building {city} business websites?', answer: 'Always. Over 65% of local searches in {city} happen on mobile devices, and Google uses mobile-first indexing — meaning your mobile experience determines your search rankings, not your desktop version. We design the mobile experience first, then expand to tablet and desktop. This ensures {city} customers on phones get the fastest, most intuitive experience possible, which directly impacts both conversion rates and your position in local search results across {county}.' },
    ],
  },
  {
    slug: 'hosting',
    name: 'Agent & App Hosting',
    shortName: 'Hosting',
    searchIntentName: 'Web Hosting Provider',
    category: 'websites-apps',
    categoryLabel: 'Websites & Apps',
    icon: '☁️',
    parentHref: '/websites-apps/hosting',
    tagline: 'Enterprise-grade hosting for AI agents and web applications',
    description: 'Managed hosting infrastructure for AI agents, web applications, and business-critical systems. Edge-deployed for speed, monitored 24/7, and scaled automatically to handle traffic spikes.',
    features: ['Edge deployment (global CDN)', 'Automatic scaling', '24/7 uptime monitoring', 'SSL/security included', 'Daily backups', 'AI agent hosting'],
    keywordTemplates: ['web hosting {city}', 'managed hosting {city}', 'app hosting {city} {state}', 'AI agent hosting {city}', 'cloud hosting {city}'],
    faqTemplates: [
      { question: 'Why does hosting quality matter for {city} business websites?', answer: 'Hosting directly impacts your website speed, uptime, and search rankings. Google measures page load speed as a ranking factor — a slow host means lower rankings in the {city} market. Our edge-deployed hosting serves your site from the closest data center to each visitor, delivering sub-second load times for {city} customers and search engine crawlers. The difference between cheap shared hosting and our managed infrastructure is measurable in both rankings and conversion rates.' },
      { question: 'What is AI agent hosting?', answer: 'AI agent hosting is specialized infrastructure for running autonomous AI systems — content generators, review responders, outreach agents, and analytics monitors — that work for your {city} business 24/7. These agents need reliable, always-on compute environments with API access, scheduled execution, and monitoring. We manage the infrastructure so your AI agents run without interruption while you focus on serving {city} customers.' },
      { question: 'How much does managed hosting cost for a {city} business?', answer: 'Managed hosting for {city} business websites starts at $50/month for standard sites and scales to $200-$500/month for high-traffic applications or AI agent hosting. This includes edge deployment across a global CDN, automatic SSL, daily backups, 24/7 uptime monitoring, security patches, and performance optimization. Compare this to the hidden costs of cheap shared hosting — slow load times, downtime during traffic spikes, and security vulnerabilities that cost {city} businesses far more in lost leads and reputation damage.' },
      { question: 'What is the difference between shared hosting and managed hosting for {city} businesses?', answer: 'Shared hosting puts your {city} business website on a server with hundreds of other sites — when any of them spike in traffic or get hacked, your site suffers. Managed hosting provides dedicated resources, edge deployment (your site loads from the nearest data center to each visitor), automatic scaling during traffic spikes, proactive security monitoring, and expert support. For {city} businesses that depend on their website for leads and revenue, managed hosting eliminates the risks that cheap hosting creates.' },
      { question: 'Can you migrate my existing {city} business website to your hosting?', answer: 'Yes — we handle the full migration process for {city} businesses, including DNS configuration, SSL setup, content transfer, database migration, email continuity, and performance optimization on the new infrastructure. We test everything in a staging environment before switching DNS, so your {city} customers experience zero downtime during the transition. Most migrations complete within 24-48 hours, and we monitor closely for 30 days post-migration to catch any issues.' },
    ],
  },

  // ── Demand Generation ───────────────────────────────────────
  {
    slug: 'local-seo',
    name: 'Local SEO & Google Maps',
    shortName: 'Local SEO',
    searchIntentName: 'Local SEO Expert',
    category: 'demand-generation',
    categoryLabel: 'Demand Generation',
    icon: '📍',
    parentHref: '/demand-generation/local-seo',
    tagline: 'Dominate local search and the Google Map Pack',
    description: 'Comprehensive local SEO strategy covering Google Business Profile optimization, local citation building, on-page optimization, and Map Pack ranking. We target the highest-intent searches in your city and own the results.',
    features: ['Google Business Profile optimization', 'Local citation building & cleanup', 'Map Pack ranking strategy', 'On-page local SEO', 'Review velocity management', 'Local link building'],
    keywordTemplates: ['local SEO {city}', 'SEO agency {city} {state}', 'Google Maps optimization {city}', 'local search marketing {city}', 'SEO company {city}', '{city} SEO services', 'Google Business Profile {city}'],
    faqTemplates: [
      { question: 'How long does it take to rank in local search results in {city}?', answer: 'Most {city} businesses see measurable ranking improvements within 30-60 days, with significant Map Pack visibility by month three. Local SEO results depend on your starting position, competitive landscape in {city}, and the strength of your Google Business Profile. Our three-layer approach — traditional SEO + GEO for AI search + Map Pack optimization — accelerates results by building visibility across all discovery channels simultaneously rather than focusing on just one.' },
      { question: 'What is the Google Map Pack and why does it matter for {city} businesses?', answer: 'The Google Map Pack is the top-3 local business listings that appear with a map when someone searches for local services — like "dentist {city}" or "plumber near me." For {city} businesses, the Map Pack captures 42% of all clicks on local search results. If your business isn\'t in the Map Pack for your primary service categories, you\'re invisible to nearly half of all potential customers searching in {city}. Our local SEO strategy specifically targets Map Pack rankings for your highest-value service categories.' },
      { question: 'How much does local SEO cost for a {city} business?', answer: 'Local SEO management for {city} businesses typically starts at $800 per month and scales based on competitive intensity and service area size. This includes Google Business Profile optimization, citation management, on-page SEO, content creation, and review velocity strategy. For businesses serving multiple cities across {county}, investment scales with the number of target markets. The ROI is typically 3-10x — our {city} clients average a 10x increase in lead volume within 6 months.' },
      { question: 'Do I need local SEO if I already have a Google Business Profile in {city}?', answer: 'Having a Google Business Profile is step one — optimizing it is where the competitive advantage lives. Over 90% of {city} businesses have claimed their GBP but fewer than 10% have fully optimized it. Optimization includes complete attribute selection, regular posting, Q&A management, photo optimization, review velocity strategy, and citation consistency across 50+ directories. The difference between a claimed GBP and an optimized one is the difference between page 3 and the Map Pack.' },
      { question: 'What makes Demand Signals different from other SEO agencies serving {city}?', answer: 'Three things: First, we\'re based in {county} — we know the {city} market, your competitors, and the local search landscape personally. Second, we don\'t just do SEO — we optimize across all three discovery layers (SEO + GEO + AEO) so your {city} business appears in Google, AI Overviews, and answer engines like ChatGPT and Perplexity simultaneously. Third, our AI agent swarms handle the ongoing work — content publishing, review responses, citation monitoring — 24/7 without the overhead of a marketing team.' },
    ],
  },
  {
    slug: 'geo-aeo-llm-optimization',
    name: 'GEO & LLM Optimization',
    shortName: 'GEO/AEO',
    searchIntentName: 'AI Search Optimization Expert',
    category: 'demand-generation',
    categoryLabel: 'Demand Generation',
    icon: '🔍',
    parentHref: '/demand-generation/geo-aeo-llm-optimization',
    tagline: 'Get cited by ChatGPT, Gemini, Perplexity, and AI Overviews',
    description: 'Generative Engine Optimization (GEO) and Answer Engine Optimization (AEO) — the new frontier of search visibility. We build the structured data, entity authority, and citation network that gets your business recommended by AI systems.',
    features: ['AI Overview optimization', 'ChatGPT/Perplexity citation building', 'Structured data & schema markup', 'Entity authority signals', 'llms.txt implementation', 'Citation network building'],
    keywordTemplates: ['GEO optimization {city}', 'AI search optimization {city}', 'LLM optimization {city}', 'ChatGPT optimization {city}', 'answer engine optimization {city} {state}', 'AI Overviews {city}'],
    faqTemplates: [
      { question: 'What is GEO optimization and why do {city} businesses need it?', answer: 'GEO (Generative Engine Optimization) is the practice of optimizing your business to appear in AI-generated search results — Google AI Overviews, ChatGPT, Gemini, Perplexity, and other answer engines. AI Overviews now appear on 48%+ of Google searches, and where they appear, organic click-through rates drop 61%. For {city} businesses, this means traditional SEO alone is no longer sufficient. GEO ensures your business is cited when AI systems synthesize answers about services in {city} and {county}.' },
      { question: 'How does GEO differ from traditional SEO for {city} businesses?', answer: 'Traditional SEO rewards keyword optimization, backlinks, and page authority. GEO rewards structured data, factual density, entity consistency, and extractable content formats. A page ranking #1 in traditional search may never appear in an AI Overview if it lacks structured data. Conversely, a page at position #5 with superior structure may be the primary source for AI-generated answers about {city} services. We optimize for both simultaneously.' },
      { question: 'What is llms.txt and should my {city} business implement it?', answer: 'llms.txt is an emerging web standard — similar to robots.txt — that provides AI models with a structured overview of your business, services, and key information. Fewer than 5% of businesses have implemented it. For {city} businesses, implementing llms.txt gives AI systems a clear, authoritative source of information about what you do, where you serve, and how to recommend you. It\'s a free, one-time implementation that provides immediate advantage over {city} competitors who haven\'t adopted it.' },
      { question: 'How long does it take to see results from GEO optimization in {city}?', answer: 'GEO optimization results for {city} businesses typically appear faster than traditional SEO — many clients see AI citation improvements within 2-4 weeks of implementing structured data, schema markup, and entity optimization. AI systems re-index and update their knowledge bases more frequently than traditional search engines. However, building strong entity authority in the {city} and {county} market is an ongoing process. The businesses that invest consistently in GEO alongside SEO build a compounding visibility advantage that becomes increasingly difficult for competitors to overcome.' },
      { question: 'How much does GEO and LLM optimization cost for a {city} business?', answer: 'GEO and LLM optimization for {city} businesses typically starts at $1,000-$2,500 per month as part of a comprehensive search visibility strategy. Initial setup — including schema markup implementation, llms.txt deployment, entity optimization, and citation network building — is a one-time investment of $2,000-$5,000. The ongoing monthly investment covers continuous content optimization, structured data maintenance, citation monitoring, and adaptation to the rapidly evolving AI search landscape. For {city} businesses, GEO optimization delivers ROI by capturing the growing share of search traffic that AI systems now mediate.' },
    ],
  },
  {
    slug: 'geo-targeting',
    name: 'Geo-Targeting & Precision Campaigns',
    shortName: 'Geo-Targeting',
    searchIntentName: 'Geo-Targeting Specialist',
    category: 'demand-generation',
    categoryLabel: 'Demand Generation',
    icon: '🎯',
    parentHref: '/demand-generation/geo-targeting',
    tagline: 'Reach customers in specific neighborhoods and service areas',
    description: 'Precision geo-targeted campaigns that reach customers in specific neighborhoods, zip codes, and service areas. Multi-channel demand generation configured for your exact market geography.',
    features: ['Zip code-level targeting', 'Neighborhood campaigns', 'Multi-channel demand gen', 'Service area optimization', 'Commuter market targeting', 'Seasonal geo-campaigns'],
    keywordTemplates: ['geo-targeting {city}', 'targeted marketing {city}', 'location-based marketing {city} {state}', 'neighborhood marketing {city}', 'zip code marketing {city}'],
    faqTemplates: [
      { question: 'How does geo-targeting work for {city} businesses?', answer: 'Geo-targeting allows your marketing to reach customers in specific locations — down to the zip code or neighborhood level. For {city} businesses, this means running different campaigns for different areas: targeting high-income neighborhoods with premium service messaging, reaching commuters along major corridors, or capturing tourists visiting specific areas of {county}. Our AI systems continuously optimize targeting based on which geographic segments convert best for your business.' },
      { question: 'Can I target customers in multiple cities from my {city} location?', answer: 'Absolutely. Most {city} businesses serve customers across multiple communities in {county} and beyond. We build multi-location geo-targeting strategies that capture demand in every area you serve — with city-specific landing pages, localized content, and targeted campaigns for each market. Our AI systems manage the complexity of multi-city campaigns without additional workload on your end.' },
      { question: 'How much does geo-targeted marketing cost for a {city} business?', answer: 'Geo-targeted marketing campaigns for {city} businesses typically start at $1,500-$3,000 per month, scaling with the number of target areas and campaign channels. This includes audience research, geographic segmentation, city-specific landing page creation, campaign management, and performance optimization. For {city} businesses expanding into new areas of {county}, geo-targeting delivers measurable ROI by concentrating your marketing budget on the exact neighborhoods where your ideal customers live and work — eliminating waste on audiences outside your service area.' },
      { question: 'What results can a {city} business expect from geo-targeting?', answer: 'Geo-targeted campaigns for {city} businesses typically deliver 2-4x higher conversion rates compared to broad, untargeted marketing. By focusing on specific neighborhoods, zip codes, and commuter corridors in {county}, every marketing dollar reaches people who can actually become customers. Our {city} clients commonly see 30-50% reductions in cost-per-lead within the first 60 days of implementing geo-targeted strategies, because the targeting eliminates spend on audiences outside your service area.' },
      { question: 'Does geo-targeting work for service-area businesses in {city}?', answer: 'Geo-targeting is especially powerful for service-area businesses in {city} — plumbers, electricians, landscapers, home services, and other businesses that travel to customers. We build campaigns that target the specific neighborhoods and communities you serve across {county}, adjusting messaging and offers based on each area. For example, a {city} HVAC company might run different campaigns for affluent neighborhoods (premium service messaging) versus newer developments (installation-focused messaging), maximizing conversion rates in each segment.' },
    ],
  },
  {
    slug: 'gbp-admin',
    name: 'Google Business Profile Administration',
    shortName: 'GBP Admin',
    searchIntentName: 'Google Business Profile Manager',
    category: 'demand-generation',
    categoryLabel: 'Demand Generation',
    icon: '📊',
    parentHref: '/demand-generation/gbp-admin',
    tagline: 'Full-service Google Business Profile management and optimization',
    description: 'Complete Google Business Profile management — from initial optimization to ongoing posting, Q&A management, review responses, and performance tracking. Your GBP is your most powerful local marketing asset; we make sure it\'s working at maximum capacity.',
    features: ['Complete profile optimization', 'Weekly GBP posts', 'Q&A management', 'Review response management', 'Category & attribute optimization', 'Performance reporting'],
    keywordTemplates: ['Google Business Profile {city}', 'GBP management {city}', 'Google My Business {city} {state}', 'GBP optimization {city}', 'Google Maps listing {city}'],
    faqTemplates: [
      { question: 'How important is Google Business Profile for {city} businesses?', answer: 'Google Business Profile is the single most important local marketing asset for {city} businesses. It determines whether you appear in the Map Pack, Google Maps, and local search results. Over 80% of consumers who search for local businesses on Google visit or contact a business within 24 hours. For {city} businesses, a fully optimized GBP with active posting, reviews, and Q&A management is the foundation of local visibility. Without it, every other marketing investment delivers diminished returns.' },
      { question: 'How often should a {city} business post on Google Business Profile?', answer: 'We recommend posting to your Google Business Profile at least twice per week — and our AI agents can handle this automatically. Regular posting signals to Google that your {city} business is active and engaged, which directly influences Map Pack rankings. Posts should include a mix of service highlights, promotions, local community content, and customer success stories. Our AI content agents generate and publish GBP posts on a consistent schedule, tuned to {city} and {county} market relevance.' },
      { question: 'How much does Google Business Profile management cost in {city}?', answer: 'Professional GBP management for {city} businesses starts at $500-$800 per month. This covers complete profile optimization, twice-weekly posting, Q&A monitoring and responses, review response management, category and attribute optimization, photo updates, and monthly performance reporting. For {city} businesses that rely on local customers, GBP management delivers some of the highest ROI of any marketing investment — a fully optimized profile with consistent activity directly drives Map Pack visibility and phone calls.' },
      { question: 'Can AI manage my Google Business Profile in {city}?', answer: 'Yes — our AI agents handle the majority of GBP management tasks for {city} businesses automatically. AI generates and schedules posts with locally relevant content, drafts professional responses to reviews within minutes of posting, monitors and answers Q&A questions, and tracks ranking changes across {city} and {county} search terms. Human oversight ensures quality and handles edge cases, but the AI automation means your GBP stays active 24/7 without requiring your time or attention.' },
      { question: 'What is included in GBP optimization for a {city} business?', answer: 'Full GBP optimization for a {city} business includes: complete business information audit, primary and secondary category selection, attribute optimization (100+ available attributes most businesses miss), service and product catalog setup, photo optimization with geo-tagged images, business description rewrite targeting {city} keywords, Q&A seeding with common customer questions, review response templates, posting schedule setup, and citation consistency verification across 50+ directories. Most {city} businesses have fewer than 30% of available GBP features properly configured.' },
    ],
  },
  {
    slug: 'systems',
    name: 'Demand Generation Systems',
    shortName: 'Demand Systems',
    searchIntentName: 'Demand Generation Agency',
    category: 'demand-generation',
    categoryLabel: 'Demand Generation',
    icon: '⚡',
    parentHref: '/demand-generation/systems',
    tagline: 'End-to-end demand generation infrastructure for sustained growth',
    description: 'Complete demand generation systems that combine SEO, GEO, content, social, and outreach into a unified, AI-powered growth engine. Not individual tactics — an integrated system that compounds results over time.',
    features: ['Integrated multi-channel system', 'AI-powered lead nurture', 'Automated follow-up sequences', 'Performance analytics dashboard', 'Conversion optimization', 'Quarterly strategy reviews'],
    keywordTemplates: ['demand generation {city}', 'lead generation {city} {state}', 'marketing system {city}', 'growth marketing {city}', 'demand gen agency {city}'],
    faqTemplates: [
      { question: 'What is a demand generation system for {city} businesses?', answer: 'A demand generation system is an integrated marketing infrastructure that combines website, SEO, content, social media, reviews, outreach, and analytics into a single, AI-powered growth engine. For {city} businesses, this means every marketing channel works together — your blog content supports your SEO, your reviews support your GBP rankings, your social media supports your brand authority, and AI agents coordinate it all 24/7. Individual tactics deliver incremental results; an integrated system delivers compounding growth.' },
      { question: 'How much does a demand generation system cost for a {city} business?', answer: 'Comprehensive demand generation systems for {city} businesses typically range from $2,500 to $8,000 per month, depending on the number of channels, content volume, and competitive intensity in your {county} market. This replaces the cost of multiple individual services — SEO agency, content writer, social media manager, review management tool, and outreach software — with a single integrated system managed by AI agents. Most {city} businesses find the integrated system costs 40-60% less than assembling equivalent capabilities from separate vendors.' },
      { question: 'How long does it take to see results from a demand generation system in {city}?', answer: 'Demand generation systems for {city} businesses typically show initial results within 30-60 days — increased content output, more consistent social presence, faster review responses, and improved GBP activity. Significant lead generation improvements usually materialize by month 3-4 as SEO rankings improve, content library builds, and review velocity accelerates. By month 6, the compounding effect kicks in — each channel reinforces the others, creating a flywheel that generates increasingly more leads with the same investment. Our {city} clients average a 3-5x increase in qualified leads within 6 months.' },
      { question: 'What makes a demand generation system different from hiring a marketing agency in {city}?', answer: 'Traditional marketing agencies assign human teams to execute tasks during business hours. A demand generation system uses AI agents that operate 24/7 — publishing content, responding to reviews, managing social media, and nurturing leads around the clock. For {city} businesses, this means faster execution (AI responds to reviews in minutes, not days), more consistent output (no sick days, vacations, or turnover), and lower cost (AI agents cost a fraction of human marketing teams). You get enterprise-level marketing output at small business pricing.' },
      { question: 'Can a demand generation system be customized for my {city} industry?', answer: 'Absolutely. Every demand generation system we build for {city} businesses is configured for your specific industry, target audience, service area, and competitive landscape in {county}. A {city} dental practice gets a system optimized for patient acquisition keywords, review generation, and appointment booking. A {city} home services company gets a system focused on emergency search terms, service area pages, and seasonal campaigns. The AI agents are trained on your industry\'s specific patterns, terminology, and customer behaviors.' },
    ],
  },

  // ── Content & Social ────────────────────────────────────────
  {
    slug: 'ai-content-generation',
    name: 'AI Content Generation',
    shortName: 'AI Content',
    searchIntentName: 'AI Content Writer',
    category: 'content-social',
    categoryLabel: 'Content & Social',
    icon: '✍️',
    parentHref: '/content-social/ai-content-generation',
    tagline: 'City-specific content published on a consistent schedule',
    description: 'AI-powered content generation that publishes city-specific blog posts, service pages, and local guides on a consistent schedule. Builds topical authority and captures long-tail organic traffic month after month.',
    features: ['City-specific blog content', 'Consistent publishing schedule', 'Long-tail keyword targeting', 'Topical authority building', 'Content calendar management', 'Performance tracking'],
    keywordTemplates: ['AI content generation {city}', 'content marketing {city} {state}', 'blog writing service {city}', 'content creation {city}', 'AI copywriting {city}'],
    faqTemplates: [
      { question: 'How does AI content generation work for {city} businesses?', answer: 'Our AI content agents research your industry, analyze {city} market trends, identify high-value keywords, and generate optimized blog posts, service pages, and local guides on a consistent publishing schedule. Each piece of content is tailored to the {city} and {county} market — referencing local competitors, neighborhoods, seasonal patterns, and search behaviors. Human editors review every piece before publication to ensure accuracy, brand voice, and quality. The result is a steady stream of content that builds topical authority and captures long-tail search traffic for your {city} business.' },
      { question: 'How much content should a {city} business publish per month?', answer: 'We recommend a minimum of 8-12 pieces of content per month for {city} businesses in competitive markets. This includes a mix of blog posts, service area pages, FAQ content, and seasonal guides. Consistency matters more than volume — our AI agents maintain a reliable publishing schedule that builds momentum over time. Within 3-6 months, this content library creates a compounding SEO advantage that competitors without consistent publishing cannot match.' },
      { question: 'How much does AI content generation cost for a {city} business?', answer: 'AI content generation for {city} businesses typically ranges from $800 to $2,500 per month depending on volume and content types. This includes topic research, keyword targeting, content creation, human editorial review, publishing, and performance tracking. Compare this to hiring a freelance writer ($50-$150 per article) or a full-time content marketer ($4,000-$6,000/month). Our AI content systems deliver 8-12+ pieces of optimized content monthly at a fraction of the cost of traditional content production.' },
      { question: 'Is AI-generated content good enough for {city} business websites?', answer: 'When properly directed and edited, AI-generated content outperforms most human-written business content in SEO metrics. Our process combines AI generation with human editorial oversight — the AI handles research, structure, keyword optimization, and drafting, while human editors ensure accuracy, brand voice, and local relevance to {city} and {county}. The result is content that is factually accurate, locally relevant, SEO-optimized, and published at a consistency that human-only teams cannot sustain.' },
      { question: 'What types of content does AI generate for {city} businesses?', answer: 'Our AI content agents produce a full range of content for {city} businesses: blog posts targeting local and industry keywords, service area pages for cities across {county}, FAQ content optimized for AI search citations, seasonal guides and trend articles, Google Business Profile posts, social media content, email newsletters, and case study frameworks. Each piece is tailored to {city} market specifics — local competitors, neighborhood references, seasonal patterns, and the search terms {city} customers actually use.' },
    ],
  },
  {
    slug: 'ai-social-media-management',
    name: 'AI Social Media Management',
    shortName: 'Social Media',
    searchIntentName: 'AI Social Media Manager',
    category: 'content-social',
    categoryLabel: 'Content & Social',
    icon: '📱',
    parentHref: '/content-social/ai-social-media-management',
    tagline: 'Automated social media across all platforms',
    description: 'AI-powered social media management that keeps your brand active and visible across all platforms — without adding to your workload. Content creation, scheduling, community engagement, and performance tracking on autopilot.',
    features: ['Multi-platform automation', 'Branded content creation', 'Community engagement', 'Hashtag optimization', 'Analytics & reporting', 'Local market targeting'],
    keywordTemplates: ['social media management {city}', 'social media marketing {city} {state}', 'social media agency {city}', 'Instagram marketing {city}', 'Facebook marketing {city}'],
    faqTemplates: [
      { question: 'How does AI social media management work for {city} businesses?', answer: 'Our AI agents create branded social media content, schedule posts across all platforms (Facebook, Instagram, LinkedIn, Google Business Profile), engage with comments and messages, and track performance metrics — all automatically. For {city} businesses, this means a consistent, professional social media presence without hiring a social media manager. The AI creates location-specific content relevant to {city} and {county} audiences and publishes on optimal schedules for maximum engagement.' },
      { question: 'How much does AI social media management cost for a {city} business?', answer: 'AI social media management for {city} businesses starts at $800-$1,500 per month covering 3-5 platforms. This includes content creation, scheduling, community engagement, hashtag optimization, and monthly analytics reporting. Compare this to hiring a social media manager ($3,000-$5,000/month) or a social media agency ($2,000-$4,000/month). Our AI-powered approach delivers more consistent posting frequency and faster community engagement at a fraction of the cost of human-managed alternatives.' },
      { question: 'Which social media platforms matter most for {city} businesses?', answer: 'For most {city} local businesses, the priority platforms are: (1) Google Business Profile — directly impacts local search rankings and Map Pack visibility. (2) Facebook — still the highest-reach platform for local audiences in {county}. (3) Instagram — essential for businesses with visual appeal (restaurants, home services, retail). (4) LinkedIn — important for B2B and professional services in {city}. We analyze your specific industry and {city} customer demographics to recommend the right platform mix rather than spreading effort across every network.' },
      { question: 'How often should a {city} business post on social media?', answer: 'We recommend {city} businesses post at least 3-5 times per week across their primary platforms for consistent visibility. Our AI agents can maintain daily posting schedules without the burnout that causes most {city} businesses to abandon social media within months. Consistency matters more than frequency — a business that posts 3 times weekly for 12 months will dramatically outperform one that posts daily for 2 months and then stops. Our AI agents never lose momentum, ensuring your {city} business maintains a steady social presence year-round.' },
      { question: 'Can AI handle customer comments and messages on social media for my {city} business?', answer: 'Yes — our AI agents monitor comments, messages, and mentions across all platforms and respond professionally within minutes. For {city} businesses, fast response times on social media directly impact customer perception and conversion rates. The AI handles routine inquiries (hours, pricing, location, booking), flags urgent issues for human attention, and maintains your brand voice across every interaction. For complex customer service situations, the AI routes conversations to your team with full context so no inquiry falls through the cracks.' },
    ],
  },
  {
    slug: 'ai-review-auto-responders',
    name: 'AI Review Auto Responders',
    shortName: 'Review Management',
    searchIntentName: 'AI Review Management Service',
    category: 'content-social',
    categoryLabel: 'Content & Social',
    icon: '⭐',
    parentHref: '/content-social/ai-review-auto-responders',
    tagline: '24/7 AI-powered review monitoring and professional responses',
    description: 'AI agents that monitor reviews across every platform, draft professional responses within minutes, request reviews from satisfied customers, and protect your online reputation 24/7.',
    features: ['24/7 review monitoring', 'Professional AI responses', 'Automated review requests', 'Multi-platform coverage', 'Sentiment analysis', 'Reputation reporting'],
    keywordTemplates: ['review management {city}', 'reputation management {city} {state}', 'review response service {city}', 'online reputation {city}', 'Google review management {city}'],
    faqTemplates: [
      { question: 'Why is review management critical for {city} businesses?', answer: 'Reviews are the #1 factor consumers use to choose local businesses — and AI search systems use them as primary data when forming recommendations. For {city} businesses, review volume, recency, and specificity directly impact both your Google Map Pack ranking and whether AI assistants like ChatGPT recommend your business. Businesses with 200+ reviews and active response rates are cited by AI systems dramatically more often than businesses with fewer or unmanaged reviews. Our AI review management system ensures every review gets a professional response within minutes, and satisfied customers receive automated review requests.' },
      { question: 'How much does AI review management cost for a {city} business?', answer: 'AI review management for {city} businesses typically ranges from $500 to $1,200 per month depending on review volume and the number of platforms monitored. This covers 24/7 monitoring across Google, Yelp, Facebook, and industry-specific platforms, professional AI-drafted responses, automated review request campaigns, sentiment analysis, and monthly reputation reporting. For {city} businesses, the ROI is direct — each additional positive review improves your Map Pack ranking and increases the likelihood of AI systems recommending your business.' },
      { question: 'How quickly does AI respond to reviews for {city} businesses?', answer: 'Our AI review agents respond to new reviews within 5-15 minutes of posting, 24 hours a day, 7 days a week. For {city} businesses, this speed matters — Google rewards businesses that respond quickly to reviews, and customers notice when a business engages promptly. Negative reviews get immediate, professional responses that demonstrate accountability and invite resolution. Positive reviews get personalized thank-you responses that reinforce the customer relationship. This response speed is impossible to maintain with manual processes.' },
      { question: 'Can AI help a {city} business get more reviews?', answer: 'Yes — our system includes automated review request campaigns that identify satisfied customers and send personalized review requests at the optimal time. For {city} businesses, we integrate with your CRM, booking system, or point-of-sale to trigger review requests after positive interactions. The AI personalizes each request based on the service provided and the customer\'s experience. Most {city} businesses see a 3-5x increase in monthly review volume within the first 60 days of implementing automated review requests.' },
      { question: 'How does AI handle negative reviews for {city} businesses?', answer: 'Our AI review agents draft professional, empathetic responses to negative reviews that acknowledge the concern, take responsibility where appropriate, and invite the customer to resolve the issue offline. For {city} businesses, the response to a negative review matters more than the review itself — 45% of consumers say they are more likely to visit a business that responds constructively to negative feedback. The AI flags critical reviews for your immediate attention while ensuring no negative review goes unanswered for more than 15 minutes.' },
    ],
  },
  {
    slug: 'ai-auto-blogging',
    name: 'AI Auto Blogging',
    shortName: 'Auto Blogging',
    searchIntentName: 'AI Blog Writer',
    category: 'content-social',
    categoryLabel: 'Content & Social',
    icon: '📝',
    parentHref: '/content-social/ai-auto-blogging',
    tagline: 'Automated blog content published on your schedule',
    description: 'Fully automated blog publishing system that researches trending topics, generates SEO-optimized posts, and publishes them on your website on a consistent schedule — building authority while you focus on your business.',
    features: ['Automated topic research', 'SEO-optimized drafts', 'Scheduled publishing', 'Category & tag management', 'Internal linking strategy', 'Performance monitoring'],
    keywordTemplates: ['AI blogging {city}', 'automated blog {city} {state}', 'blog content service {city}', 'AI blog writing {city}', 'content automation {city}'],
    faqTemplates: [
      { question: 'What is AI auto blogging for {city} businesses?', answer: 'AI auto blogging is a fully automated content system that researches trending topics in your industry, generates SEO-optimized blog posts targeting {city} and {county} keywords, and publishes them on your website on a consistent schedule. Each post is designed to capture long-tail search traffic and build topical authority in your niche. For {city} businesses, this means a steady stream of fresh, relevant content without spending hours writing — building the content depth that both Google and AI search systems reward.' },
      { question: 'How much does AI auto blogging cost for a {city} business?', answer: 'AI auto blogging for {city} businesses typically costs $600-$1,500 per month depending on posting frequency and content depth. A standard plan includes 8-12 posts per month, each targeting specific {city} and {county} keywords, with human editorial review before publication. Compare this to hiring a freelance blogger ($400-$1,200 per month for 4 posts) — our AI system delivers 2-3x the content volume with better keyword optimization and zero management overhead on your end.' },
      { question: 'How does AI auto blogging improve SEO for {city} businesses?', answer: 'Consistent blog publishing is one of the strongest signals Google uses to determine site authority and freshness. For {city} businesses, AI auto blogging builds a library of locally-relevant content that targets hundreds of long-tail keywords — searches like "best {city} [service] for [situation]" that individually have low volume but collectively drive significant traffic. After 6-12 months, this content library creates a compounding SEO advantage: each new post strengthens internal linking, builds topical authority, and captures search terms that competitors without consistent content will never rank for.' },
      { question: 'Do I need to review AI-generated blog posts before they publish?', answer: 'Our system includes human editorial review by default — every post is checked for accuracy, brand voice, and local relevance to {city} and {county} before publication. You can also opt into an approval workflow where posts are sent to you for review before going live. Most {city} business owners prefer the fully managed approach after reviewing the first few posts and confirming the quality meets their standards. The AI learns your preferences over time, producing content that increasingly matches your voice and priorities.' },
      { question: 'What topics does AI auto blogging cover for {city} businesses?', answer: 'Our AI researches trending topics in your industry, analyzes what {city} customers are searching for, identifies content gaps your competitors haven\'t covered, and generates posts that address real customer questions. Topics include seasonal service guides, local market insights, how-to articles, industry news analysis, FAQ-style posts targeting voice search, and service comparison content. For {city} businesses, every post is localized — referencing {city} neighborhoods, {county} market conditions, and regional specifics that make the content genuinely useful to local readers.' },
    ],
  },
  {
    slug: 'ai-content-repurposing',
    name: 'AI Content Repurposing',
    shortName: 'Content Repurposing',
    searchIntentName: 'Content Repurposing Service',
    category: 'content-social',
    categoryLabel: 'Content & Social',
    icon: '🔄',
    parentHref: '/content-social/ai-content-repurposing',
    tagline: 'Turn one piece of content into ten across every platform',
    description: 'AI-powered content repurposing that takes your best content and transforms it across formats — blog posts become social media threads, videos become articles, webinars become email sequences. Maximum reach from minimum input.',
    features: ['Cross-platform adaptation', 'Format transformation', 'Social media snippets', 'Email sequence creation', 'Video-to-text conversion', 'Infographic generation'],
    keywordTemplates: ['content repurposing {city}', 'content marketing {city} {state}', 'content strategy {city}', 'multi-platform content {city}', 'content distribution {city}'],
    faqTemplates: [
      { question: 'How does content repurposing benefit {city} businesses?', answer: 'Content repurposing multiplies the value of every piece of content you create. A single blog post about services in {city} can become 5-10 social media posts, a GBP update, an email newsletter segment, and a video script — all without additional research or creative work. For {city} businesses with limited marketing resources, repurposing is the highest-leverage content strategy available. Our AI agents handle the transformation automatically, ensuring consistent brand voice across every platform and format.' },
      { question: 'How much does AI content repurposing cost for a {city} business?', answer: 'AI content repurposing for {city} businesses typically ranges from $500 to $1,500 per month depending on the volume of source content and the number of output formats. Each piece of source content generates 5-10 derivative pieces across platforms, making the effective cost per content piece extremely low. For {city} businesses already investing in blog content or video, repurposing maximizes the return on that existing investment by extending reach to audiences on platforms you are not currently active on.' },
      { question: 'What content formats can be repurposed for {city} businesses?', answer: 'Our AI repurposing agents transform content across virtually any format: blog posts become social media carousels, LinkedIn articles, email newsletter segments, and GBP posts. Video content becomes blog articles, social clips, quote graphics, and podcast scripts. Webinar recordings become article series, FAQ pages, and lead magnets. For {city} businesses, we prioritize the formats that perform best in your local market — ensuring repurposed content reaches {city} and {county} audiences on the platforms where they actually engage.' },
      { question: 'How quickly does AI repurpose content for {city} businesses?', answer: 'Our AI agents can transform a single blog post or video into 5-10 platform-specific pieces within hours — a process that would take a human content team 1-2 full days. For {city} businesses, this speed means your content reaches audiences across all platforms while it is still timely and relevant. When you publish a blog post about a seasonal topic in {city}, the repurposed social media posts, email content, and GBP updates can go live the same day rather than trickling out over weeks.' },
      { question: 'Does repurposed content hurt SEO for {city} businesses?', answer: 'No — when done correctly, repurposed content strengthens SEO rather than hurting it. Our AI agents do not simply copy-paste content across platforms. Each repurposed piece is adapted to the platform\'s format, audience expectations, and SEO requirements. Blog-to-social transformations create unique captions and hooks. Blog-to-email conversions restructure content for inbox engagement. For {city} businesses, repurposed content builds consistent brand signals across the web that search engines and AI systems interpret as authority and relevance in the {county} market.' },
    ],
  },

  // ── AI & Agent Services ─────────────────────────────────────
  {
    slug: 'ai-automation-strategies',
    name: 'AI Adoption Strategies',
    shortName: 'AI Strategy',
    searchIntentName: 'AI Strategy Consultant',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🧠',
    parentHref: '/ai-services/ai-automation-strategies',
    tagline: 'Strategic AI adoption roadmaps for business transformation',
    description: 'Custom AI adoption strategies that identify the highest-ROI automation opportunities in your business, build implementation roadmaps, and guide your team through the transition from manual processes to AI-powered operations.',
    features: ['AI readiness assessment', 'ROI opportunity mapping', 'Implementation roadmap', 'Team training & adoption', 'Vendor selection guidance', 'Ongoing optimization'],
    keywordTemplates: ['AI strategy {city}', 'AI consulting {city} {state}', 'AI adoption {city}', 'business automation {city}', 'AI implementation {city}'],
    faqTemplates: [
      { question: 'Where should a {city} business start with AI adoption?', answer: 'Start with the repetitive, time-consuming tasks that drain your team\'s energy without requiring creative judgment. For most {city} businesses, the highest-ROI starting points are: (1) AI review responses — immediate time savings with measurable reputation impact, (2) AI content generation — consistent publishing without hiring a writer, (3) AI-powered lead follow-up — faster response times that dramatically improve conversion rates. Our AI adoption strategy begins with a thorough assessment of your current operations and identifies the specific opportunities where AI delivers the fastest, most measurable ROI for your {city} business.' },
      { question: 'How much does an AI strategy consultation cost for a {city} business?', answer: 'AI strategy engagements for {city} businesses start with a comprehensive assessment ($2,500-$5,000) that maps your current operations, identifies automation opportunities, and delivers a prioritized implementation roadmap with projected ROI for each initiative. Ongoing AI strategy advisory services range from $1,000-$3,000 per month, covering implementation oversight, vendor evaluation, team training, and continuous optimization. For {city} businesses making their first AI investment, the strategy assessment typically pays for itself by preventing costly tool purchases that do not fit your actual workflows.' },
      { question: 'How long does it take to implement an AI strategy for a {city} business?', answer: 'A complete AI adoption roadmap for a {city} business typically takes 2-3 weeks to develop, including operational assessment, opportunity mapping, and implementation planning. Initial quick-win implementations (review management, content automation) can be live within 2-4 weeks of strategy approval. Full implementation of a comprehensive AI strategy — covering marketing, operations, and customer service — usually takes 3-6 months in phased rollouts. We prioritize the highest-ROI implementations first so your {city} business sees measurable results within the first month.' },
      { question: 'Is my {city} business ready for AI adoption?', answer: 'Most {city} businesses are more ready than they think. You do not need technical staff or existing AI infrastructure to start. The prerequisites are: (1) a functioning website, (2) a Google Business Profile, (3) at least one person who can approve content and review AI outputs, and (4) clarity on which business outcomes matter most. Our readiness assessment evaluates your {city} business across 20+ criteria and identifies exactly where AI will have the biggest impact — whether that is marketing automation, customer service, or operational efficiency.' },
      { question: 'What ROI can a {city} business expect from AI adoption?', answer: 'ROI varies by implementation, but our {city} clients consistently see: 20-40 hours per week saved in marketing and administrative labor, 3-5x increase in content output, 60-80% faster response times to reviews and customer inquiries, and 2-4x improvement in lead generation within 6 months. The key insight is that AI does not just save time — it enables activities that {city} businesses simply could not do before due to resource constraints. A 5-person {city} business can achieve the marketing output of a 20-person operation with the right AI strategy.' },
    ],
  },
  {
    slug: 'ai-workforce-automation',
    name: 'AI Workforce Automation',
    shortName: 'AI Automation',
    searchIntentName: 'AI Automation Expert',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🤖',
    parentHref: '/ai-services/ai-workforce-automation',
    tagline: 'Replace repetitive work with AI — keep the humans for what matters',
    description: 'AI systems that replace repetitive marketing, administrative, and operational tasks — freeing your team to focus on high-value work. Not a single tool; an integrated automation layer across your business.',
    features: ['Process automation', 'Workflow optimization', 'Task delegation to AI', 'Integration with existing tools', 'Performance monitoring', 'Continuous optimization'],
    keywordTemplates: ['AI automation {city}', 'business automation {city} {state}', 'workflow automation {city}', 'AI workforce {city}', 'process automation {city}'],
    faqTemplates: [
      { question: 'What tasks can AI automate for {city} businesses?', answer: 'For most {city} businesses, AI can automate: review monitoring and responses, social media content creation and scheduling, lead follow-up sequences, appointment reminders, content publishing, citation monitoring, analytics reporting, email marketing, and customer FAQ responses. The key principle is automating tasks that are repetitive, rule-based, and time-consuming while keeping human judgment for strategic decisions, complex customer interactions, and creative direction. Our {city} clients typically save 20-40 hours per week in marketing labor through AI automation.' },
      { question: 'How much does AI workforce automation cost for a {city} business?', answer: 'AI workforce automation for {city} businesses typically ranges from $1,500 to $5,000 per month depending on the number of processes automated and integration complexity. Compare this to the fully loaded cost of the employees or contractors currently performing those tasks — most {city} businesses find that AI automation delivers the same or better output at 20-40% of the human labor cost. The investment includes setup, integration with your existing tools, ongoing monitoring, and continuous optimization of automated workflows.' },
      { question: 'Will AI automation replace my {city} business employees?', answer: 'AI workforce automation is designed to replace tasks, not people. For {city} businesses, automation handles the repetitive, time-consuming work that prevents your team from focusing on high-value activities — customer relationships, strategic decisions, creative work, and business development. Most {city} business owners find that AI automation allows their existing team to accomplish significantly more, improving both business output and employee satisfaction by eliminating the drudge work nobody enjoys.' },
      { question: 'How long does it take to implement AI automation for a {city} business?', answer: 'Simple automations — review responses, social media scheduling, content publishing — can be live within 1-2 weeks for {city} businesses. More complex workflow automations involving CRM integration, multi-step sequences, and custom business logic typically take 3-6 weeks. We implement in phases, starting with the highest-ROI automations first so your {city} business sees results quickly while we build out the full automation infrastructure. Each phase is tested and refined before moving to the next.' },
      { question: 'What tools and systems does AI automation integrate with for {city} businesses?', answer: 'Our AI automation integrates with the tools {city} businesses already use: Google Workspace, Microsoft 365, CRM platforms (Salesforce, HubSpot, Pipedrive), booking systems (Calendly, Acuity, ServiceTitan), accounting software (QuickBooks, Xero), communication platforms (Slack, email), social media platforms, review sites, and custom internal tools via API. We audit your existing tech stack and build automations that connect your systems without requiring you to change tools or learn new platforms.' },
    ],
  },
  {
    slug: 'ai-agent-infrastructure',
    name: 'AI Agent Infrastructure',
    shortName: 'AI Infrastructure',
    searchIntentName: 'AI Infrastructure Provider',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🏗️',
    parentHref: '/ai-services/ai-agent-infrastructure',
    tagline: 'The infrastructure layer that makes AI agents reliable and scalable',
    description: 'Enterprise-grade infrastructure for deploying, monitoring, and scaling AI agents — the technical foundation that makes autonomous AI operations reliable, secure, and maintainable for business-critical workflows.',
    features: ['Agent deployment pipelines', 'Monitoring & alerting', 'Scaling infrastructure', 'Security & compliance', 'API orchestration', 'Failover & redundancy'],
    keywordTemplates: ['AI infrastructure {city}', 'AI agent setup {city}', 'AI deployment {city} {state}', 'AI systems {city}', 'AI operations {city}'],
    faqTemplates: [
      { question: 'What is AI agent infrastructure and do {city} businesses need it?', answer: 'AI agent infrastructure is the technical foundation — hosting, orchestration, monitoring, and security — that allows AI agents to run reliably 24/7 for your {city} business. Just like a website needs hosting, AI agents need infrastructure to operate. For {city} businesses deploying AI review responders, content agents, or outreach systems, proper infrastructure ensures your agents run without interruption, handle edge cases gracefully, and scale as your business grows. We manage all infrastructure so you focus on results, not technical operations.' },
      { question: 'How much does AI agent infrastructure cost for a {city} business?', answer: 'AI agent infrastructure for {city} businesses typically ranges from $500 to $2,000 per month depending on the number of agents deployed, API usage volume, and compute requirements. This covers hosting, orchestration, monitoring, security, scaling, and maintenance. For {city} businesses running multiple AI agents (content, reviews, social, outreach), the infrastructure cost is a fraction of what those agents save in labor — typically 5-10% of the equivalent human labor cost for the same output.' },
      { question: 'Is AI agent infrastructure secure for {city} businesses handling sensitive data?', answer: 'Security is built into every layer of our AI agent infrastructure. For {city} businesses handling customer data, we implement encryption at rest and in transit, API key rotation, access logging, audit trails, and role-based access controls. Agents operate within isolated environments with least-privilege access — they can only reach the systems and data they need to perform their specific function. For {city} businesses in regulated industries (healthcare, finance, legal), we configure infrastructure to meet HIPAA, SOC 2, or industry-specific compliance requirements.' },
      { question: 'What happens if an AI agent fails for my {city} business?', answer: 'Our infrastructure includes automated failover, retry logic, and alerting for all AI agents running for {city} businesses. If an agent encounters an error — API timeout, unexpected data format, rate limiting — the system automatically retries with exponential backoff. If failures persist, the system alerts our monitoring team and falls back to safe defaults (queuing tasks for retry rather than dropping them). For {city} businesses, this means your AI operations are resilient — a temporary API outage does not result in missed reviews, unpublished content, or lost leads.' },
      { question: 'Can you scale AI agent infrastructure as my {city} business grows?', answer: 'Yes — scalability is a core design principle of our AI agent infrastructure. For {city} businesses expanding their service area across {county} or adding new AI capabilities, the infrastructure scales horizontally without downtime or re-architecture. Adding a new city to your geo-targeting agents, increasing content volume, or deploying additional outreach agents requires configuration changes, not infrastructure rebuilds. Most {city} businesses start with 2-3 agents and scale to 8-12 within the first year as they see results from each deployment.' },
    ],
  },
  {
    slug: 'ai-automated-outreach',
    name: 'AI Powered Outreach',
    shortName: 'AI Outreach',
    searchIntentName: 'AI Lead Generation Service',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '📧',
    parentHref: '/ai-services/ai-automated-outreach',
    tagline: 'Automated prospecting and lead generation that runs 24/7',
    description: 'AI-powered outreach systems that research prospects, craft personalized messages, manage follow-up sequences, and route qualified responses to your inbox. Enterprise-level lead generation without the SDR team.',
    features: ['Automated prospect research', 'Personalized message crafting', 'Multi-step sequences', 'Response classification', 'CRM integration', 'Performance optimization'],
    keywordTemplates: ['AI outreach {city}', 'automated lead generation {city} {state}', 'AI prospecting {city}', 'lead gen automation {city}', 'outreach automation {city}'],
    faqTemplates: [
      { question: 'How does AI outreach work for {city} businesses?', answer: 'Our AI outreach system researches potential customers in {city} and {county}, identifies businesses or individuals matching your ideal client profile, crafts personalized messages based on their specific situation, sends multi-step outreach sequences, classifies responses (interested, not now, not interested), and routes qualified leads directly to your inbox or CRM. For {city} businesses, this replaces the need for a dedicated SDR (Sales Development Representative) — delivering the same outreach volume at a fraction of the cost, running 24/7 without sick days or turnover.' },
      { question: 'How much does AI outreach cost for a {city} business?', answer: 'AI outreach systems for {city} businesses typically range from $1,500 to $4,000 per month depending on outreach volume, number of channels (email, LinkedIn, direct mail), and prospect research depth. Compare this to hiring an SDR ($4,000-$7,000/month fully loaded) or outsourcing to a lead gen agency ($3,000-$8,000/month). Our AI outreach delivers higher volume, more consistent follow-up, and better personalization at a lower cost — running 24/7 without the management overhead of a human sales team.' },
      { question: 'Is AI outreach compliant with anti-spam laws for {city} businesses?', answer: 'Yes — compliance is built into our AI outreach systems. All outreach campaigns for {city} businesses comply with CAN-SPAM, GDPR (for international contacts), and platform-specific policies. This includes proper opt-out mechanisms, accurate sender identification, relevant content requirements, and respect for unsubscribe requests. Our AI systems automatically manage suppression lists, honor opt-out requests immediately, and adjust messaging to stay within platform guidelines. For {city} businesses, this means effective outreach without legal risk.' },
      { question: 'What results can a {city} business expect from AI outreach?', answer: 'AI outreach campaigns for {city} businesses typically generate: 15-25% open rates on cold email, 3-8% positive response rates, and 10-30 qualified conversations per month depending on your industry and target audience in {county}. Response rates improve over time as the AI learns which messaging, timing, and prospect segments convert best for your specific {city} business. Most clients see their first qualified leads within 2-3 weeks of campaign launch and reach steady-state lead flow by month two.' },
      { question: 'Can AI outreach target specific industries or neighborhoods in {city}?', answer: 'Yes — precision targeting is a core capability of our AI outreach system. For {city} businesses, we can target prospects by industry vertical, company size, geographic area (specific neighborhoods or zip codes in {county}), job title, business age, online presence quality, and dozens of other criteria. A {city} commercial cleaning company might target new businesses that opened in the last 6 months. A {city} IT services firm might target medical practices with outdated websites. The AI researches each prospect individually to craft messages relevant to their specific situation.' },
    ],
  },
  {
    slug: 'ai-agent-swarms',
    name: 'AI Agent Swarms',
    shortName: 'Agent Swarms',
    searchIntentName: 'AI Marketing Agent Provider',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🐝',
    parentHref: '/ai-services/ai-agent-swarms',
    tagline: 'Networks of AI agents handling your entire marketing operation',
    description: 'Coordinated networks of AI agents handling content creation, review management, social media, outreach, and analytics simultaneously — running 24/7 without a team. One monthly cost replaces multiple vendors and marketing employees.',
    features: ['Multi-agent coordination', '24/7 autonomous operation', 'Content + reviews + social + outreach', 'Replaces multiple vendors', 'Continuous optimization', 'Monthly performance reporting'],
    keywordTemplates: ['AI agent swarms {city}', 'AI marketing agents {city} {state}', 'automated marketing {city}', 'AI marketing system {city}', 'marketing automation {city}'],
    faqTemplates: [
      { question: 'What are AI agent swarms and how do they help {city} businesses?', answer: 'AI agent swarms are coordinated networks of specialized AI agents that handle different aspects of your marketing simultaneously — one agent publishes content, another manages reviews, another runs social media, another handles outreach, and another monitors analytics. For {city} businesses, this means enterprise-level marketing output without the enterprise-level cost. One monthly investment replaces what would otherwise require 3-5 marketing employees or multiple agency retainers. Our {city} clients typically see their marketing output increase 5-10x while their cost decreases by 60-80% compared to traditional approaches.' },
      { question: 'How much do AI agent swarms cost for {city} businesses?', answer: 'AI agent swarm packages for {city} businesses typically range from $2,000 to $5,000 per month depending on the number and complexity of agents deployed. Compare this to the cost of hiring even a single marketing employee ($4,000-$8,000/month fully loaded) or retaining multiple specialist agencies ($5,000-$15,000/month combined). For {city} businesses looking to compete with larger companies that have dedicated marketing departments, agent swarms provide the most cost-effective path to comprehensive marketing coverage.' },
      { question: 'How many AI agents does a typical {city} business need?', answer: 'Most {city} businesses start with 3-5 core agents covering the highest-impact functions: a content agent (blog and service pages), a review agent (monitoring and responses), a social agent (multi-platform posting), a GBP agent (Google Business Profile management), and an analytics agent (performance tracking and reporting). As results materialize, businesses typically expand to 8-12 agents adding outreach, email nurture, citation monitoring, and competitive intelligence. We recommend starting focused and expanding based on measured ROI rather than deploying everything at once.' },
      { question: 'How do AI agent swarms coordinate for {city} businesses?', answer: 'Our agent swarms use an orchestration layer that ensures all agents work together rather than in isolation. For {city} businesses, this coordination is critical — when your content agent publishes a new blog post, the social agent automatically creates promotion posts, the GBP agent references the content in updates, and the email agent includes it in the next newsletter. When your review agent detects a surge in positive reviews, the content agent generates a case study. This coordination creates a marketing flywheel that no collection of disconnected tools can replicate.' },
      { question: 'How long does it take to deploy AI agent swarms for a {city} business?', answer: 'Initial deployment of a core agent swarm for a {city} business takes 2-4 weeks. The first week covers discovery — analyzing your business, competitors, target audience in {county}, and existing marketing assets. Weeks two and three involve configuring, training, and testing each agent against your specific requirements. Week four is a supervised launch where agents operate with human review before transitioning to autonomous operation. Additional agents can be added incrementally as you see results and identify new automation opportunities in your {city} market.' },
    ],
  },
  {
    slug: 'private-llms',
    name: 'AI Private LLMs',
    shortName: 'Private LLMs',
    searchIntentName: 'Private AI Model Provider',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🔒',
    parentHref: '/ai-services/private-llms',
    tagline: 'Private, secure AI language models for your business data',
    description: 'Private LLM deployments that keep your business data, customer information, and proprietary knowledge secure — while giving your team the power of AI language models tuned to your specific industry and operations.',
    features: ['Private model deployment', 'Business data security', 'Custom fine-tuning', 'Knowledge base integration', 'Team access management', 'Compliance & audit trails'],
    keywordTemplates: ['private LLM {city}', 'private AI {city} {state}', 'secure AI {city}', 'custom AI model {city}', 'enterprise AI {city}'],
    faqTemplates: [
      { question: 'What is a private LLM and why would a {city} business need one?', answer: 'A private LLM is an AI language model deployed exclusively for your business — your data never leaves your environment and is never used to train other models. For {city} businesses handling sensitive customer data (medical practices, law firms, financial advisors), a private LLM provides the productivity benefits of AI without the data security risks of public AI services. Your team can ask questions about internal documents, generate content from proprietary knowledge, and automate workflows — all within a secure, private environment.' },
      { question: 'How much does a private LLM cost for a {city} business?', answer: 'Private LLM deployments for {city} businesses typically range from $2,000 to $10,000 per month depending on model size, usage volume, and infrastructure requirements. This includes model hosting, fine-tuning on your business data, knowledge base integration, team access management, and ongoing maintenance. For {city} businesses in regulated industries where data security is non-negotiable — healthcare, legal, financial services — the investment is justified by the combination of AI productivity gains and complete data privacy that public AI services cannot guarantee.' },
      { question: 'Can a private LLM be trained on my {city} business data?', answer: 'Yes — that is one of the primary advantages of a private LLM. We fine-tune the model on your business documents, SOPs, customer communication history, product catalogs, and industry knowledge. For {city} businesses, this means the AI understands your specific services, pricing, service areas in {county}, competitive positioning, and brand voice. A fine-tuned private LLM generates more accurate, relevant responses than a general-purpose AI because it has been specifically trained on how your {city} business operates.' },
      { question: 'How secure is a private LLM for {city} businesses?', answer: 'Private LLMs provide the highest level of AI data security available. Your {city} business data is processed on isolated infrastructure — it is never sent to third-party API providers, never used to train public models, and never accessible to other users. We implement encryption at rest and in transit, access controls with audit logging, and compliance configurations for HIPAA, SOC 2, or other regulatory requirements. For {city} businesses in healthcare, legal, or financial services, a private LLM is the only way to leverage AI while maintaining full regulatory compliance.' },
      { question: 'What can my {city} business team do with a private LLM?', answer: 'A private LLM enables your {city} business team to: search and query internal documents using natural language, generate customer communications in your brand voice, draft proposals and reports from templates and past work, answer employee questions about company policies and procedures, analyze customer feedback patterns, create training materials from existing documentation, and automate repetitive writing tasks. The model understands your business context, so outputs require minimal editing — your team gets AI-powered productivity without sacrificing accuracy or brand consistency.' },
    ],
  },
  {
    slug: 'clawbot-setup',
    name: 'AI Clawbot Setup',
    shortName: 'Clawbot',
    searchIntentName: 'Competitive Intelligence Service',
    category: 'ai-services',
    categoryLabel: 'AI & Agents',
    icon: '🦀',
    parentHref: '/ai-services/clawbot-setup',
    tagline: 'AI-powered web scraping and competitive intelligence',
    description: 'Custom web scraping and competitive intelligence systems powered by AI — monitoring competitor pricing, tracking market changes, aggregating industry data, and delivering actionable intelligence to your inbox.',
    features: ['Competitor monitoring', 'Price tracking', 'Market intelligence', 'Data aggregation', 'Automated alerts', 'Custom dashboards'],
    keywordTemplates: ['competitive intelligence {city}', 'market research {city} {state}', 'competitor monitoring {city}', 'business intelligence {city}', 'AI data collection {city}'],
    faqTemplates: [
      { question: 'How can competitive intelligence help my {city} business?', answer: 'Competitive intelligence gives you real-time visibility into what your {city} competitors are doing — their pricing, their content strategy, their review velocity, their search rankings, and their marketing tactics. Our Clawbot systems automatically monitor competitor websites, GBP profiles, social media, and review platforms, delivering actionable intelligence to your inbox. For {city} businesses in competitive markets, this intelligence informs pricing decisions, content strategy, and marketing investment — ensuring you\'re always one step ahead.' },
      { question: 'How much does competitive intelligence cost for a {city} business?', answer: 'Clawbot competitive intelligence for {city} businesses typically ranges from $800 to $2,500 per month depending on the number of competitors monitored, data sources tracked, and reporting frequency. This includes automated monitoring of competitor websites, GBP profiles, review platforms, social media, and search rankings, plus weekly intelligence reports delivered to your inbox. For {city} businesses in competitive markets across {county}, the intelligence gained typically informs decisions worth many multiples of the monitoring investment.' },
      { question: 'What data does Clawbot collect for {city} businesses?', answer: 'Clawbot monitors multiple data streams relevant to your {city} competitive landscape: competitor website changes (pricing, services, content updates), Google Business Profile activity (posts, reviews, rating changes), review velocity across platforms (Google, Yelp, Facebook, industry sites), social media posting frequency and engagement, search ranking positions for your target keywords in {city}, new competitor entries into the {county} market, and industry trend data. All data is aggregated into actionable intelligence reports — not raw data dumps — so you can make informed decisions quickly.' },
      { question: 'Is web scraping legal for {city} businesses?', answer: 'The web scraping our Clawbot performs for {city} businesses is focused on publicly available information — the same data anyone could access by visiting a website or searching Google. We monitor public web pages, public review profiles, public social media posts, and public search results. Our systems respect robots.txt directives, rate limit requests to avoid server impact, and comply with applicable terms of service. For {city} businesses, competitive intelligence gathered from public sources is a standard and legal business practice used by companies of all sizes.' },
      { question: 'How quickly does Clawbot detect competitor changes in {city}?', answer: 'Clawbot monitors competitor activity on configurable intervals — from hourly to daily depending on the data source and your needs. For {city} businesses, critical changes (pricing updates, new service launches, negative review spikes) are detected within hours and flagged in real-time alerts. Routine monitoring (content publishing, social media activity, ranking changes) is summarized in weekly intelligence reports. This means your {city} business can respond to competitor moves within days rather than discovering them months later.' },
    ],
  },
]

export const SERVICE_SLUGS = SERVICES.map(s => s.slug)

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return SERVICES.find(s => s.slug === slug)
}

export function getServicesByCategory(category: ServiceCategory): ServiceData[] {
  return SERVICES.filter(s => s.category === category)
}
