import { feedHeaders, checkConditional, getDetailLevel, SITE_URL } from '@/lib/feed-utils'

export async function GET(request: Request) {
  const detail = getDetailLevel(request)

  let md: string

  if (detail === 'summary') {
    md = [
      '# Accessibility Statement — Demand Signals',
      '',
      'Last updated: April 7, 2026',
      '',
      '> Our commitment to digital accessibility and WCAG 2.1 Level AA conformance.',
      '',
      '## Sections',
      '',
      '- Our Commitment',
      '- Conformance Standard (WCAG 2.1 Level AA)',
      '- What We Have Done (Structure, Visual Design, Keyboard, Images, Forms, Performance)',
      '- Known Limitations',
      '- Assistive Technology Compatibility',
      '- Assessment Methods',
      '- Reporting an Accessibility Issue',
      '- Formal Complaints',
      '- Applicable Laws and Standards',
      '- Continuous Improvement',
      '',
      `**Full statement:** [Accessibility](${SITE_URL}/accessibility)  `,
      `**Full markdown:** [Accessibility Feed (full)](${SITE_URL}/feeds/pages/accessibility?detail=full)`,
      '',
      '---',
      '',
      `*[Demand Signals](${SITE_URL}) — AI-Powered Demand Generation*`,
      '',
      `**View on website:** [Accessibility](${SITE_URL}/accessibility)  `,
      `**All services:** [Services Directory](${SITE_URL}/feeds/services.md)  `,
      `**All FAQs:** [Master FAQ](${SITE_URL}/faqs.md)  `,
      `**Blog:** [Blog Index](${SITE_URL}/feeds/blog.md)  `,
      `**Content API:** [content-index.json](${SITE_URL}/content-index.json)`,
    ].join('\n')
  } else {
    md = [
      '# Accessibility Statement — Demand Signals',
      '',
      'Last updated: April 7, 2026',
      '',
      '## Our Commitment',
      '',
      'Demand Signals is committed to ensuring our website and digital services are accessible to all people, including individuals with visual, auditory, cognitive, motor, and neurological disabilities. We believe digital accessibility is a fundamental requirement — not an optional feature — and we treat it as an ongoing responsibility in every aspect of our design and development process.',
      '',
      'As an AI-powered agency that builds websites and applications for clients, we hold ourselves to the same standards we recommend to the businesses we serve.',
      '',
      '## Conformance Standard',
      '',
      'We are actively working toward full conformance with the **Web Content Accessibility Guidelines (WCAG) 2.1, Level AA**, published by the World Wide Web Consortium (W3C). WCAG 2.1 Level AA is the standard referenced by the Americans with Disabilities Act (ADA) and Section 508 of the Rehabilitation Act, as well as accessibility regulations in the European Union, Canada, Australia, and many other jurisdictions.',
      '',
      'Our current status is **partially conformant** — meaning the majority of our website conforms to WCAG 2.1 Level AA, with specific exceptions documented below that we are actively working to resolve.',
      '',
      '## What We Have Done',
      '',
      '### Structure and Navigation',
      '',
      '- Semantic HTML5 elements (header, nav, main, section, footer, article) throughout all pages',
      '- Logical heading hierarchy (h1 through h6) on every page for screen reader navigation',
      '- ARIA landmarks and roles on interactive components (navigation menus, dropdowns, accordions)',
      '- Skip-to-content link for keyboard users to bypass repeated navigation',
      '- Breadcrumb navigation with proper schema markup on all service and location pages',
      '',
      '### Visual Design',
      '',
      '- Minimum contrast ratio of 4.5:1 for normal text and 3:1 for large text against all backgrounds',
      '- No information conveyed by color alone — all status indicators include text labels or icons',
      '- Readable base font size (16px) with responsive scaling using clamp() for comfortable reading on all devices',
      '- Clear visual focus indicators on all interactive elements (links, buttons, form fields)',
      '- Resizable text — all content remains functional at 200% browser zoom',
      '',
      '### Keyboard Accessibility',
      '',
      '- All interactive elements (links, buttons, form controls, dropdowns, accordions) are fully operable with keyboard alone',
      '- Logical tab order following the visual layout of each page',
      '- Dropdown navigation menus support Enter/Space to open, Escape to close, and Tab/Arrow keys to navigate items',
      '- No keyboard traps — focus can always move freely through and out of any component',
      '',
      '### Images and Media',
      '',
      '- Descriptive alt text on all meaningful images',
      '- Decorative images marked with empty alt attributes or aria-hidden to exclude them from screen reader announcements',
      '- SVG icons include accessible titles or are hidden from assistive technology when purely decorative',
      '',
      '### Forms and Interactive Elements',
      '',
      '- All form fields have associated labels (via label elements or aria-label attributes)',
      '- Form validation errors are announced to screen readers and displayed visually near the relevant field',
      '- Required fields are clearly indicated both visually and programmatically',
      '- FAQ accordions use proper ARIA expanded/collapsed states and are operable with keyboard',
      '',
      '### Performance and Compatibility',
      '',
      '- Server-side rendering (Next.js SSR/SSG) ensures content is available to screen readers without waiting for JavaScript execution',
      '- Pages are structured to degrade gracefully if JavaScript fails to load',
      '- Tested with major screen readers (NVDA, VoiceOver) and keyboard-only navigation',
      '',
      '## Known Limitations',
      '',
      '### Animated Canvas Elements',
      '',
      'Hero sections use an HTML5 Canvas particle animation that cannot be paused by users. Users with motion sensitivity or vestibular disorders may find this uncomfortable. **Planned fix:** Add a prefers-reduced-motion media query to disable canvas animations and replace with a static gradient background.',
      '',
      '### Scroll-triggered Animations',
      '',
      'Some page sections use Framer Motion scroll-triggered fade-in and slide-in animations. While these are brief and subtle, they may present issues for users with motion sensitivity. **Planned fix:** Implement prefers-reduced-motion detection in our ScrollReveal component to disable transitions when the user\'s OS-level motion preference is set to reduced.',
      '',
      '### Third-Party Embedded Content',
      '',
      'Our Google Calendar booking widget and any embedded third-party tools may not fully meet WCAG 2.1 Level AA standards. These components are controlled by external providers. We provide alternative contact methods (phone, email) for users who cannot interact with embedded widgets.',
      '',
      '### PDF Reports',
      '',
      'Intelligence reports generated by our tools may not be fully accessible in PDF format. **Planned fix:** Offer HTML-based report views as an alternative to PDF downloads.',
      '',
      '## Assistive Technology Compatibility',
      '',
      'Our website is designed to be compatible with the following assistive technologies:',
      '',
      '- **Screen readers:** NVDA (Windows), VoiceOver (macOS/iOS), TalkBack (Android)',
      '- **Browser magnification:** All major browsers at up to 200% zoom',
      '- **Keyboard navigation:** Full site navigation without mouse',
      '- **Voice control:** Basic compatibility with Dragon NaturallySpeaking and Voice Control (macOS)',
      '',
      'Our website is designed to work with current and recent versions of major browsers (Chrome, Firefox, Safari, Edge).',
      '',
      '## Assessment Methods',
      '',
      'Demand Signals assesses website accessibility through:',
      '',
      '- **Automated testing:** Lighthouse accessibility audits and axe-core analysis during development and deployment.',
      '- **Manual testing:** Keyboard-only navigation testing, screen reader testing (NVDA, VoiceOver), and visual inspection of color contrast and focus indicators.',
      '- **Code review:** Accessibility checks are part of our development process — semantic HTML, ARIA attributes, and alt text are reviewed before deployment.',
      '- **User feedback:** We incorporate accessibility-related feedback from users into our improvement roadmap and prioritize reported issues.',
      '',
      '## Reporting an Accessibility Issue',
      '',
      'If you encounter an accessibility barrier on our website, we want to hear about it. Please provide as much detail as possible:',
      '',
      '- The web page URL where you encountered the issue',
      '- A description of the problem and what you were trying to do',
      '- The assistive technology and browser you were using (if applicable)',
      '- Your preferred format for our response (email, phone, etc.)',
      '',
      '**Contact:**',
      '- Email: DemandSignals@gmail.com (subject: Accessibility Issue)',
      '- Phone: (916) 542-2423',
      '- We aim to respond to accessibility reports within 2 business days.',
      '',
      '## Formal Complaints',
      '',
      'If you are not satisfied with our response to an accessibility concern, you may:',
      '',
      '- Escalate your complaint by emailing DemandSignals@gmail.com with "Accessibility Complaint" in the subject line. All complaints are reviewed by management.',
      '- File a complaint with the U.S. Department of Justice, Civil Rights Division, Disability Rights Section.',
      '- Contact your state\'s attorney general or relevant regulatory body.',
      '',
      '## Applicable Laws and Standards',
      '',
      'This accessibility statement considers the following laws and standards:',
      '',
      '- **Americans with Disabilities Act (ADA)** — Title III, as interpreted to apply to websites as places of public accommodation',
      '- **Section 508 of the Rehabilitation Act** — Applicable to federal agencies and contractors; we follow its technical standards as a best practice',
      '- **Web Content Accessibility Guidelines (WCAG) 2.1** — Our target conformance level is AA',
      '- **California Unruh Civil Rights Act** — Requires full and equal access to business establishments, including websites',
      '- **European Accessibility Act (EAA)** — For clients and visitors in the EU, we strive to meet the accessibility requirements outlined in EN 301 549',
      '',
      '## Continuous Improvement',
      '',
      'Accessibility is not a one-time project — it is an ongoing commitment. We regularly audit our website, incorporate new accessibility best practices, and update this statement as improvements are made. Our goal is full WCAG 2.1 Level AA conformance across all pages and components.',
      '',
      'As an agency that builds websites for other businesses, we are committed to leading by example. The accessibility standards we apply to our own site inform the standards we recommend and implement for our clients.',
      '',
      '---',
      '',
      `*[Demand Signals](${SITE_URL}) — AI-Powered Demand Generation*`,
      '',
      `**View on website:** [Accessibility](${SITE_URL}/accessibility)  `,
      `**All services:** [Services Directory](${SITE_URL}/feeds/services.md)  `,
      `**All FAQs:** [Master FAQ](${SITE_URL}/faqs.md)  `,
      `**Blog:** [Blog Index](${SITE_URL}/feeds/blog.md)  `,
      `**Content API:** [content-index.json](${SITE_URL}/content-index.json)`,
    ].join('\n')
  }

  const cached = checkConditional(request, md)
  if (cached) return cached

  return new Response(md, {
    status: 200,
    headers: feedHeaders('text/markdown', md),
  })
}
