'use client'
import Link from 'next/link'
import { HERO_VIDEO_URL, BOOKING_URL } from '@/lib/constants'

export function HeroVideo() {
  return (
    <section
      aria-label="Hero"
      style={{ position: 'relative', minHeight: '92vh', display: 'flex', alignItems: 'center', overflow: 'hidden', background: 'var(--dark)' }}
    >
      {/* Video background */}
      <div aria-hidden="true" style={{ position: 'absolute', inset: 0 }}>
        <video
          autoPlay muted loop playsInline preload="metadata"
          style={{ width: '100%', height: '100%', objectFit: 'cover', opacity: 0.35 }}
        >
          <source src={HERO_VIDEO_URL} type="video/mp4" />
        </video>
        <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, rgba(29,35,48,0.92) 0%, rgba(29,35,48,0.7) 100%)' }} />
      </div>

      {/* Content */}
      <div style={{ position: 'relative', zIndex: 2, maxWidth: 1200, margin: '0 auto', padding: '120px 24px 80px', width: '100%' }}>
        <span style={{
          display: 'inline-block', background: 'rgba(104,197,173,0.15)', color: 'var(--teal)',
          padding: '5px 16px', borderRadius: 100, fontSize: '0.78rem', fontWeight: 700,
          letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 28,
        }}>
          AI-First Demand Generation — Northern California &amp; Beyond
        </span>

        <h1 style={{ color: '#fff', fontSize: 'clamp(2.4rem, 5vw, 4rem)', lineHeight: 1.1, marginBottom: 28, maxWidth: 700 }}>
          We Make You<br />
          <span style={{ color: 'var(--teal)' }}>The Signal,</span><br />
          <span style={{ color: 'var(--orange)' }}>Not The Noise.</span>
        </h1>

        <p style={{ color: 'rgba(255,255,255,0.78)', fontSize: 'clamp(1rem,1.5vw,1.2rem)', maxWidth: 620, marginBottom: 40, lineHeight: 1.65 }}>
          Your website, built by AI experts. Your content, generated by AI. Your reviews, handled by AI. Your social media, run by AI. You approve — AI does the rest.
        </p>

        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          <Link href="/contact" style={{
            display: 'inline-flex', alignItems: 'center', padding: '16px 36px',
            background: 'linear-gradient(135deg, var(--teal), var(--teal-dark))',
            color: '#fff', fontWeight: 700, fontSize: '1.05rem', borderRadius: 10,
            boxShadow: '0 4px 24px rgba(104,197,173,0.4)',
          }}>
            Get Started Free →
          </Link>
          <a href={BOOKING_URL} target="_blank" rel="noopener" style={{
            display: 'inline-flex', alignItems: 'center', padding: '15px 34px',
            border: '2px solid rgba(255,255,255,0.4)', color: '#fff',
            fontWeight: 600, fontSize: '1.05rem', borderRadius: 10,
          }}>
            Book a Free Call
          </a>
        </div>
      </div>

      {/* Scroll hint */}
      <div aria-hidden="true" style={{
        position: 'absolute', bottom: 32, left: '50%', transform: 'translateX(-50%)',
        color: 'rgba(255,255,255,0.3)', fontSize: '0.75rem', letterSpacing: '0.1em',
        textTransform: 'uppercase', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
      }}>
        Scroll
        <span style={{ width: 1, height: 32, background: 'rgba(255,255,255,0.2)', display: 'block' }} />
      </div>
    </section>
  )
}
