#!/usr/bin/env node
// ── Generate services_catalog seed SQL from TS CATALOG ─────────────
// Reads src/lib/quote-pricing.ts CATALOG + computes displayPriceCents
// where not explicit, and emits a single SQL file that UPSERTs every
// item into services_catalog.
//
// Usage:
//   npx tsx scripts/generate-services-catalog-seed.mjs > supabase/migrations/014b_services_catalog_seed.sql
//   (or redirect wherever you want)
//
// Safe to re-run: uses ON CONFLICT DO UPDATE so re-seeds refresh fields.

import { getCatalog } from '../src/lib/quote-pricing'

// Items that should auto-appear on paid-project deposit invoices as
// 100%-discounted "New Client Appreciation" lines.
const VALUE_STACK_IDS = new Set([
  'market-research',
  'competitor-analysis',
  'project-plan',
])

function esc(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (typeof v === 'number') return v.toString()
  if (Array.isArray(v) || typeof v === 'object') {
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  }
  return `'${String(v).replace(/'/g, "''")}'`
}

function midpointCents(range: readonly [number, number] | undefined): number {
  if (!range || range.length !== 2) return 0
  return Math.round((range[0] + range[1]) / 2)
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function rowFor(item: any, idx: number): string {
  const displayPrice = typeof item.displayPriceCents === 'number'
    ? item.displayPriceCents
    : midpointCents(item.baseRange)

  const values = [
    esc(item.id),
    esc(item.category),
    esc(item.name),
    esc(item.description ?? null),
    esc(item.benefit ?? null),
    esc(item.aiBadge ?? null),
    esc(item.type),
    esc(item.baseRange?.[0] ?? 0),
    esc(item.baseRange?.[1] ?? 0),
    esc(item.monthlyRange?.[0] ?? null),
    esc(item.monthlyRange?.[1] ?? null),
    esc(displayPrice),
    esc(!!item.quantifiable),
    esc(item.quantityLabel ?? null),
    esc(item.perUnitRange?.[0] ?? null),
    esc(item.perUnitRange?.[1] ?? null),
    esc(item.defaultQuantity ?? null),
    esc(item.minQuantity ?? null),
    esc(item.maxQuantity ?? null),
    esc(item.narrowingFactors ?? []),
    esc(item.timelineWeeks?.[0] ?? 0),
    esc(item.timelineWeeks?.[1] ?? 0),
    esc(item.parallelGroup ?? null),
    esc(item.dependsOn ?? []),
    esc(!!item.financeable),
    esc(item.financingTermMonths ?? null),
    esc(item.suggestsWith ?? []),
    esc(!!item.requiresBase),
    esc(item.excludes ?? []),
    esc(item.phase),
    esc(!!item.availableForBid),
    esc(item.available !== false),
    esc(VALUE_STACK_IDS.has(item.id)),
    esc(idx),
  ]
  return `  (${values.join(',\n   ')})`
}

const catalog = getCatalog()

console.log('-- 014b: Seed services_catalog with the 48 items from TS CATALOG.')
console.log('-- Generated by scripts/generate-services-catalog-seed.mjs')
console.log('-- Safe to re-run: UPSERTs on id.')
console.log('')
console.log(`INSERT INTO services_catalog (`)
console.log(`  id, category, name, description, benefit, ai_badge,`)
console.log(`  pricing_type, base_range_low_cents, base_range_high_cents,`)
console.log(`  monthly_range_low_cents, monthly_range_high_cents, display_price_cents,`)
console.log(`  quantifiable, quantity_label, per_unit_range_low_cents, per_unit_range_high_cents,`)
console.log(`  default_quantity, min_quantity, max_quantity,`)
console.log(`  narrowing_factors, timeline_weeks_low, timeline_weeks_high,`)
console.log(`  parallel_group, depends_on, financeable, financing_term_months,`)
console.log(`  suggests_with, requires_base, excludes,`)
console.log(`  phase, available_for_bid, active, included_with_paid_project, sort_order`)
console.log(`) VALUES`)
console.log(catalog.map(rowFor).join(',\n'))
console.log(`ON CONFLICT (id) DO UPDATE SET`)
console.log(`  category = EXCLUDED.category,`)
console.log(`  name = EXCLUDED.name,`)
console.log(`  description = EXCLUDED.description,`)
console.log(`  benefit = EXCLUDED.benefit,`)
console.log(`  ai_badge = EXCLUDED.ai_badge,`)
console.log(`  pricing_type = EXCLUDED.pricing_type,`)
console.log(`  base_range_low_cents = EXCLUDED.base_range_low_cents,`)
console.log(`  base_range_high_cents = EXCLUDED.base_range_high_cents,`)
console.log(`  monthly_range_low_cents = EXCLUDED.monthly_range_low_cents,`)
console.log(`  monthly_range_high_cents = EXCLUDED.monthly_range_high_cents,`)
console.log(`  display_price_cents = EXCLUDED.display_price_cents,`)
console.log(`  quantifiable = EXCLUDED.quantifiable,`)
console.log(`  quantity_label = EXCLUDED.quantity_label,`)
console.log(`  per_unit_range_low_cents = EXCLUDED.per_unit_range_low_cents,`)
console.log(`  per_unit_range_high_cents = EXCLUDED.per_unit_range_high_cents,`)
console.log(`  default_quantity = EXCLUDED.default_quantity,`)
console.log(`  min_quantity = EXCLUDED.min_quantity,`)
console.log(`  max_quantity = EXCLUDED.max_quantity,`)
console.log(`  narrowing_factors = EXCLUDED.narrowing_factors,`)
console.log(`  timeline_weeks_low = EXCLUDED.timeline_weeks_low,`)
console.log(`  timeline_weeks_high = EXCLUDED.timeline_weeks_high,`)
console.log(`  parallel_group = EXCLUDED.parallel_group,`)
console.log(`  depends_on = EXCLUDED.depends_on,`)
console.log(`  financeable = EXCLUDED.financeable,`)
console.log(`  financing_term_months = EXCLUDED.financing_term_months,`)
console.log(`  suggests_with = EXCLUDED.suggests_with,`)
console.log(`  requires_base = EXCLUDED.requires_base,`)
console.log(`  excludes = EXCLUDED.excludes,`)
console.log(`  phase = EXCLUDED.phase,`)
console.log(`  available_for_bid = EXCLUDED.available_for_bid,`)
console.log(`  active = EXCLUDED.active,`)
console.log(`  included_with_paid_project = EXCLUDED.included_with_paid_project,`)
console.log(`  sort_order = EXCLUDED.sort_order,`)
console.log(`  updated_at = now();`)
console.log('')
console.log(`-- Apply the pricing updates per the value-stack psychology (2026-04-18):`)
console.log(`--   market-research          $750 (was $500)`)
console.log(`--   competitor-analysis      $750 (was $500)`)
console.log(`--   site-social-audit        $950 (was $750) — standalone courtesy gift`)
console.log(`--   project-plan             $1,750 — always included in paid-project value stack`)
console.log(`-- Value stack total: $750 + $750 + $1,750 = $3,250`)
console.log(`UPDATE services_catalog SET display_price_cents = 75000 WHERE id = 'market-research';`)
console.log(`UPDATE services_catalog SET display_price_cents = 75000 WHERE id = 'competitor-analysis';`)
console.log(`UPDATE services_catalog SET display_price_cents = 95000 WHERE id = 'site-social-audit';`)
console.log(`UPDATE services_catalog SET display_price_cents = 175000 WHERE id = 'project-plan';`)
