import { feedHeaders, checkConditional, getDetailLevel, SITE_URL } from '@/lib/feed-utils'

const HOME_FAQS = [
  {
    question: 'What is AI demand generation for local businesses?',
    answer: 'AI demand generation uses artificial intelligence — including AI agent swarms, automated content creation, and generative engine optimization — to attract, capture, and convert local customers across Google, AI assistants like ChatGPT, and social media. Demand Signals specializes in deploying these systems for local businesses in Northern California.',
  },
  {
    question: 'What is GEO or Generative Engine Optimization?',
    answer: 'Generative Engine Optimization (GEO) is the practice of optimizing your business to appear in AI-generated answers from tools like ChatGPT, Gemini, and Perplexity. This includes entity optimization, structured data markup, AI-friendly content structure, and citation building — all signals that help AI assistants trust and recommend your business.',
  },
  {
    question: 'How much does Demand Signals cost?',
    answer: 'Demand Signals offers custom pricing based on the services you need — AI websites, local SEO, AI agent swarms, or a full-stack demand generation retainer. Book a free 15-minute call for a no-obligation quote scoped to your specific business and market.',
  },
  {
    question: 'What areas does Demand Signals serve?',
    answer: 'Demand Signals primarily serves local businesses in El Dorado County (Placerville, El Dorado Hills, Cameron Park), Sacramento, Folsom, Placer County, and across Northern California. We work remotely with businesses throughout California.',
  },
  {
    question: 'How is Demand Signals different from a traditional marketing agency?',
    answer: 'Unlike traditional agencies that rely on manual labor, Demand Signals deploys AI agent swarms that run 24/7 — handling content creation, SEO monitoring, outreach, review management, and reporting automatically. This means faster results, lower cost, and continuous optimization without the overhead of a large marketing team.',
  },
]

export async function GET(request: Request) {
  const detail = getDetailLevel(request)

  let md: string

  if (detail === 'summary') {
    md = [
      '# Demand Signals — AI-Powered Demand Generation Agency',
      '',
      '> AI-powered websites and AI-driven marketing for local businesses. Top 3 Google ranking in 90 days. 10x more leads at a fraction of agency cost.',
      '',
      '## Service Categories',
      '',
      `- [Websites & Apps](${SITE_URL}/websites-apps) — WordPress, React/Next.js, Mobile Apps, Vibe Coding, UI/UX Design, Hosting`,
      `- [Demand Generation](${SITE_URL}/demand-generation) — LLM Optimization, Local SEO, Geo-Targeting, GBP Admin, Demand Systems`,
      `- [Content & Social](${SITE_URL}/content-social) — AI Content, Social Media, Review Management, Auto Blogging, Content Repurposing`,
      `- [AI & Agents](${SITE_URL}/ai-services) — AI Strategy, Workforce Automation, Infrastructure, Outreach, Agent Swarms, Private LLMs`,
      '',
      '---',
      '',
      `*[Demand Signals](${SITE_URL}) — AI-Powered Demand Generation*`,
      '',
      `**View on website:** [Home](${SITE_URL})  `,
      `**All services:** [Services Directory](${SITE_URL}/feeds/services.md)  `,
      `**All FAQs:** [Master FAQ](${SITE_URL}/faqs.md)  `,
      `**Blog:** [Blog Index](${SITE_URL}/feeds/blog.md)  `,
      `**Content API:** [content-index.json](${SITE_URL}/content-index.json)`,
    ].join('\n')
  } else {
    const faqsBlock = HOME_FAQS
      .map(f => `### ${f.question}\n\n${f.answer}`)
      .join('\n\n')

    md = [
      '# Demand Signals — AI-Powered Demand Generation Agency',
      '',
      '> AI-powered websites and AI-driven marketing for local businesses. Top 3 Google ranking in 90 days. 10x more leads at a fraction of agency cost.',
      '',
      '## Company Overview',
      '',
      'Demand Signals is an AI-first demand generation agency based in Northern California. We replace marketing employees and agency retainers with AI systems that run 24/7.',
      '',
      '**Your website, built by AI experts. Your content, generated by AI. Your reviews, handled by AI. Your social media, run by AI. You approve — AI does the rest.**',
      '',
      '## Homepage Sections',
      '',
      '- **Hero** — AI-Powered Demand Generation for local businesses',
      '- **Services Grid** — Four service categories covering websites, demand generation, content, and AI',
      '- **Web Presence Spectrum** — Full-spectrum online visibility across search, AI, social, and reputation',
      '- **What We Replace** — Traditional marketing roles replaced by AI systems',
      '- **Industries We Serve** — Veterinary, dental, legal, contractor, real estate, fitness, restaurant, auto, retail, education',
      '- **How It Works** — Simple process from audit to deployment to ongoing optimization',
      '- **Portfolio** — Client work across Northern California and beyond',
      '- **Client Reviews** — Real testimonials from local business clients',
      '- **Blog & News** — Latest insights on AI marketing, SEO, and demand generation',
      '- **Booking** — Schedule a free 30-minute strategy call',
      '',
      '## Service Categories',
      '',
      `### [Websites & Apps](${SITE_URL}/websites-apps)`,
      'WordPress development, React/Next.js web apps, iOS and Android mobile apps, vibe coded web apps, UI/UX design, and agent and app hosting.',
      '',
      `### [Demand Generation](${SITE_URL}/demand-generation)`,
      'LLM optimization (GEO/AEO), local SEO, geo-targeting, Google Business Profile admin, and demand generation systems.',
      '',
      `### [Content & Social](${SITE_URL}/content-social)`,
      'AI content generation, AI social media management, AI review auto responders, AI auto blogging, and AI content republishing.',
      '',
      `### [AI & Agents](${SITE_URL}/ai-services)`,
      'AI adoption strategies, AI workforce automation, AI infrastructure, AI powered outreach, AI agent swarms, private LLMs, and Clawbot setup.',
      '',
      '## Key Value Propositions',
      '',
      '- **Three-layer discovery strategy** — SEO + GEO + AEO ensures visibility across Google, AI assistants, and voice search',
      '- **AI agent swarms** — Autonomous AI systems that handle content, monitoring, outreach, and reporting 24/7',
      '- **Enterprise output, small business pricing** — AI does the heavy lifting so you pay a fraction of traditional agency costs',
      '- **Domain loop architecture** — Proprietary system that compounds authority across your digital presence',
      '- **Free tools and audits** — Demand Audit and Intelligence Reports at no cost, no obligation',
      '',
      '## Frequently Asked Questions',
      '',
      faqsBlock,
      '',
      '## Quick Links',
      '',
      `- [Book a Free Strategy Call](${SITE_URL}/contact)`,
      `- [Free Demand Audit](${SITE_URL}/tools/demand-audit)`,
      `- [Free Intelligence Reports](${SITE_URL}/tools/research-reports)`,
      `- [Our Team](${SITE_URL}/team)`,
      `- [Portfolio](${SITE_URL}/portfolio)`,
      `- [Blog & News](${SITE_URL}/blog)`,
      `- [Service Locations](${SITE_URL}/locations)`,
      '',
      '---',
      '',
      `*[Demand Signals](${SITE_URL}) — AI-Powered Demand Generation*`,
      '',
      `**View on website:** [Home](${SITE_URL})  `,
      `**All services:** [Services Directory](${SITE_URL}/feeds/services.md)  `,
      `**All FAQs:** [Master FAQ](${SITE_URL}/faqs.md)  `,
      `**Blog:** [Blog Index](${SITE_URL}/feeds/blog.md)  `,
      `**Content API:** [content-index.json](${SITE_URL}/content-index.json)`,
    ].join('\n')
  }

  const cached = checkConditional(request, md)
  if (cached) return cached

  return new Response(md, {
    status: 200,
    headers: feedHeaders('text/markdown', md),
  })
}
